/* A recursive-descent parser generated by peg 0.1.9 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 69

#include "menace/global.h"
#include "menace/parser.h"
#include "menace/scanner.h"
#include "menace/ast.h"

#include <stdio.h>

#define YY_INPUT(buf, result, max_size)                                                 \
{                                                                                       \
    int yyc = scanner_get_next_token(ctx->scanner, &ctx->token_text, &ctx->token_len);  \
    result = (T_EOF == yyc) ? 0 : (*(buf)=yyc, 1);                                      \
}

#define YY_CTX_LOCAL
#define YYSTYPE             ast_id_t
#define YY_PARSE(T)         static T

#define YY_CTX_MEMBERS                  \
    scanner_t           *scanner;       \
    context_t           *context;       \
    const char          *token_text;    \
    int                 token_len;      \
    char                *error;

#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( ctx->begin= ctx->pos, 1)
#endif
#ifndef YY_END
#define YY_END		( ctx->end= ctx->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *ctx, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *buf;
  int       buflen;
  int       pos;
  int       limit;
  char     *text;
  int       textlen;
  int       begin;
  int       end;
  int       textmax;
  yythunk  *thunks;
  int       thunkslen;
  int       thunkpos;
  YYSTYPE   yy;
  YYSTYPE  *val;
  YYSTYPE  *vals;
  int       valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext yyctx0;
yycontext *yyctx= &yyctx0;
#endif

YY_LOCAL(int) yyrefill(yycontext *ctx)
{
  int yyn;
  while (ctx->buflen - ctx->pos < 512)
    {
      ctx->buflen *= 2;
      ctx->buf= (char *)realloc(ctx->buf, ctx->buflen);
    }
  YY_INPUT((ctx->buf + ctx->pos), yyn, (ctx->buflen - ctx->pos));
  if (!yyn) return 0;
  ctx->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *ctx)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  ++ctx->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *ctx, int c)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  if ((unsigned char)ctx->buf[ctx->pos] == c)
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchChar(ctx, %c) @ %s\n", c, ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(ctx, %c) @ %s\n", c, ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *ctx, char *s)
{
  int yysav= ctx->pos;
  while (*s)
    {
      if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
      if (ctx->buf[ctx->pos] != *s)
        {
          ctx->pos= yysav;
          return 0;
        }
      ++s;
      ++ctx->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *ctx, unsigned char *bits)
{
  int c;
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  c= (unsigned char)ctx->buf[ctx->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *ctx, yyaction action, int begin, int end)
{
  while (ctx->thunkpos >= ctx->thunkslen)
    {
      ctx->thunkslen *= 2;
      ctx->thunks= (yythunk *)realloc(ctx->thunks, sizeof(yythunk) * ctx->thunkslen);
    }
  ctx->thunks[ctx->thunkpos].begin=  begin;
  ctx->thunks[ctx->thunkpos].end=    end;
  ctx->thunks[ctx->thunkpos].action= action;
  ++ctx->thunkpos;
}

YY_LOCAL(int) yyText(yycontext *ctx, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (ctx->textlen < (yyleng + 1))
	{
	  ctx->textlen *= 2;
	  ctx->text= (char *)realloc(ctx->text, ctx->textlen);
	}
      memcpy(ctx->text, ctx->buf + begin, yyleng);
    }
  ctx->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *ctx)
{
  int pos;
  for (pos= 0;  pos < ctx->thunkpos;  ++pos)
    {
      yythunk *thunk= &ctx->thunks[pos];
      int yyleng= thunk->end ? yyText(ctx, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, ctx->text));
      thunk->action(ctx, ctx->text, yyleng);
    }
  ctx->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *ctx)
{
  if ((ctx->limit -= ctx->pos))
    {
      memmove(ctx->buf, ctx->buf + ctx->pos, ctx->limit);
    }
  ctx->begin -= ctx->pos;
  ctx->end -= ctx->pos;
  ctx->pos= ctx->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *ctx, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(ctx);
      yyCommit(ctx);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *ctx, char *text, int count)  { ctx->val += count; }
YY_LOCAL(void) yyPop(yycontext *ctx, char *text, int count)   { ctx->val -= count; }
YY_LOCAL(void) yySet(yycontext *ctx, char *text, int count)   { ctx->val[count]= ctx->yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(ctx, yythunkpos0)

YY_RULE(int) yy_ERROR(yycontext *ctx); /* 69 */
YY_RULE(int) yy_EOF(yycontext *ctx); /* 68 */
YY_RULE(int) yy_DOT(yycontext *ctx); /* 67 */
YY_RULE(int) yy_OP_GTE(yycontext *ctx); /* 66 */
YY_RULE(int) yy_OP_GT(yycontext *ctx); /* 65 */
YY_RULE(int) yy_OP_LTE(yycontext *ctx); /* 64 */
YY_RULE(int) yy_OP_LT(yycontext *ctx); /* 63 */
YY_RULE(int) yy_OP_NEQ(yycontext *ctx); /* 62 */
YY_RULE(int) yy_OP_EQ(yycontext *ctx); /* 61 */
YY_RULE(int) yy_OP_POW(yycontext *ctx); /* 60 */
YY_RULE(int) yy_WHITESPACE(yycontext *ctx); /* 59 */
YY_RULE(int) yy_COLON(yycontext *ctx); /* 58 */
YY_RULE(int) yy_HASHROCKET(yycontext *ctx); /* 57 */
YY_RULE(int) yy_Dict_Pair(yycontext *ctx); /* 56 */
YY_RULE(int) yy_R_BRACE(yycontext *ctx); /* 55 */
YY_RULE(int) yy_Dict_Elements(yycontext *ctx); /* 54 */
YY_RULE(int) yy_L_BRACE(yycontext *ctx); /* 53 */
YY_RULE(int) yy_R_BRACKET(yycontext *ctx); /* 52 */
YY_RULE(int) yy_Array_Elements(yycontext *ctx); /* 51 */
YY_RULE(int) yy_L_BRACKET(yycontext *ctx); /* 50 */
YY_RULE(int) yy_Function_Args(yycontext *ctx); /* 49 */
YY_RULE(int) yy_Dict(yycontext *ctx); /* 48 */
YY_RULE(int) yy_Array(yycontext *ctx); /* 47 */
YY_RULE(int) yy_FALSE(yycontext *ctx); /* 46 */
YY_RULE(int) yy_TRUE(yycontext *ctx); /* 45 */
YY_RULE(int) yy_SYMBOL(yycontext *ctx); /* 44 */
YY_RULE(int) yy_STRING(yycontext *ctx); /* 43 */
YY_RULE(int) yy_INTEGER(yycontext *ctx); /* 42 */
YY_RULE(int) yy_Function_Call(yycontext *ctx); /* 41 */
YY_RULE(int) yy_Value(yycontext *ctx); /* 40 */
YY_RULE(int) yy_OP_DIV(yycontext *ctx); /* 39 */
YY_RULE(int) yy_OP_TIMES(yycontext *ctx); /* 38 */
YY_RULE(int) yy_Exp3(yycontext *ctx); /* 37 */
YY_RULE(int) yy_OP_MINUS(yycontext *ctx); /* 36 */
YY_RULE(int) yy_OP_PLUS(yycontext *ctx); /* 35 */
YY_RULE(int) yy_Exp2(yycontext *ctx); /* 34 */
YY_RULE(int) yy_Exp1(yycontext *ctx); /* 33 */
YY_RULE(int) yy_COMMA(yycontext *ctx); /* 32 */
YY_RULE(int) yy_Parameters(yycontext *ctx); /* 31 */
YY_RULE(int) yy_R_PAREN(yycontext *ctx); /* 30 */
YY_RULE(int) yy_Parameter_List(yycontext *ctx); /* 29 */
YY_RULE(int) yy_L_PAREN(yycontext *ctx); /* 28 */
YY_RULE(int) yy_DEF(yycontext *ctx); /* 27 */
YY_RULE(int) yy_RETURN(yycontext *ctx); /* 26 */
YY_RULE(int) yy_OP_ASSIGN(yycontext *ctx); /* 25 */
YY_RULE(int) yy_IDENT(yycontext *ctx); /* 24 */
YY_RULE(int) yy_PASS(yycontext *ctx); /* 23 */
YY_RULE(int) yy_WHILE(yycontext *ctx); /* 22 */
YY_RULE(int) yy_ELSE(yycontext *ctx); /* 21 */
YY_RULE(int) yy_ELSEIF(yycontext *ctx); /* 20 */
YY_RULE(int) yy_Block_Prelude(yycontext *ctx); /* 19 */
YY_RULE(int) yy_Expression(yycontext *ctx); /* 18 */
YY_RULE(int) yy__(yycontext *ctx); /* 17 */
YY_RULE(int) yy_IF(yycontext *ctx); /* 16 */
YY_RULE(int) yy_Else_Part(yycontext *ctx); /* 15 */
YY_RULE(int) yy_Elseif_Part(yycontext *ctx); /* 14 */
YY_RULE(int) yy_If_Part(yycontext *ctx); /* 13 */
YY_RULE(int) yy_Named_Function_Def(yycontext *ctx); /* 12 */
YY_RULE(int) yy_Return_Statement(yycontext *ctx); /* 11 */
YY_RULE(int) yy_Expression_Statement(yycontext *ctx); /* 10 */
YY_RULE(int) yy_Assign_Statement(yycontext *ctx); /* 9 */
YY_RULE(int) yy_Pass_Statement(yycontext *ctx); /* 8 */
YY_RULE(int) yy_While_Statement(yycontext *ctx); /* 7 */
YY_RULE(int) yy_If_Statement(yycontext *ctx); /* 6 */
YY_RULE(int) yy_OUTDENT(yycontext *ctx); /* 5 */
YY_RULE(int) yy_Statement(yycontext *ctx); /* 4 */
YY_RULE(int) yy_EOL(yycontext *ctx); /* 3 */
YY_RULE(int) yy_INDENT(yycontext *ctx); /* 2 */
YY_RULE(int) yy_Statement_Block(yycontext *ctx); /* 1 */


YY_RULE(int) yy_ERROR(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "ERROR"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "ERROR", ctx->buf+ctx->pos));
  return 1;
  l1:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ERROR", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", ctx->buf+ctx->pos));
  return 1;
  l2:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_DOT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "DOT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "DOT", ctx->buf+ctx->pos));
  return 1;
  l3:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DOT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_GTE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_GTE"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_GTE", ctx->buf+ctx->pos));
  return 1;
  l4:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_GTE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_GT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_GT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_GT", ctx->buf+ctx->pos));
  return 1;
  l5:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_GT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_LTE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_LTE"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_LTE", ctx->buf+ctx->pos));
  return 1;
  l6:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_LTE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_LT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_LT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_LT", ctx->buf+ctx->pos));
  return 1;
  l7:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_LT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_NEQ(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_NEQ"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_NEQ", ctx->buf+ctx->pos));
  return 1;
  l8:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_NEQ", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_EQ(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_EQ"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_EQ", ctx->buf+ctx->pos));
  return 1;
  l9:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_EQ", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_POW(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_POW"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l10;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_POW", ctx->buf+ctx->pos));
  return 1;
  l10:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_POW", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_WHITESPACE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "WHITESPACE"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;
  yyprintf((stderr, "  ok   %s @ %s\n", "WHITESPACE", ctx->buf+ctx->pos));
  return 1;
  l11:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WHITESPACE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_COLON(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "COLON"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l12;
  yyprintf((stderr, "  ok   %s @ %s\n", "COLON", ctx->buf+ctx->pos));
  return 1;
  l12:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COLON", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_HASHROCKET(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "HASHROCKET"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l13;
  yyprintf((stderr, "  ok   %s @ %s\n", "HASHROCKET", ctx->buf+ctx->pos));
  return 1;
  l13:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "HASHROCKET", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Dict_Pair(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Dict_Pair"));  if (!yy_Expression(ctx)) goto l14;  if (!yy_HASHROCKET(ctx)) goto l14;  if (!yy__(ctx)) goto l14;  if (!yy_Expression(ctx)) goto l14;
  yyprintf((stderr, "  ok   %s @ %s\n", "Dict_Pair", ctx->buf+ctx->pos));
  return 1;
  l14:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Dict_Pair", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_R_BRACE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "R_BRACE"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l15;
  yyprintf((stderr, "  ok   %s @ %s\n", "R_BRACE", ctx->buf+ctx->pos));
  return 1;
  l15:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "R_BRACE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Dict_Elements(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Dict_Elements"));  if (!yy_Dict_Pair(ctx)) goto l16;
  {  int yypos17= ctx->pos, yythunkpos17= ctx->thunkpos;  if (!yy_COMMA(ctx)) goto l17;  if (!yy__(ctx)) goto l17;  if (!yy_Dict_Pair(ctx)) goto l17;  goto l18;
  l17:;	  ctx->pos= yypos17; ctx->thunkpos= yythunkpos17;
  }
  l18:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Dict_Elements", ctx->buf+ctx->pos));
  return 1;
  l16:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Dict_Elements", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_L_BRACE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "L_BRACE"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l19;
  yyprintf((stderr, "  ok   %s @ %s\n", "L_BRACE", ctx->buf+ctx->pos));
  return 1;
  l19:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "L_BRACE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_R_BRACKET(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "R_BRACKET"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l20;
  yyprintf((stderr, "  ok   %s @ %s\n", "R_BRACKET", ctx->buf+ctx->pos));
  return 1;
  l20:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "R_BRACKET", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Array_Elements(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Array_Elements"));  if (!yy_Expression(ctx)) goto l21;
  {  int yypos22= ctx->pos, yythunkpos22= ctx->thunkpos;  if (!yy_COMMA(ctx)) goto l22;  if (!yy__(ctx)) goto l22;  if (!yy_Array_Elements(ctx)) goto l22;  goto l23;
  l22:;	  ctx->pos= yypos22; ctx->thunkpos= yythunkpos22;
  }
  l23:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Array_Elements", ctx->buf+ctx->pos));
  return 1;
  l21:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Array_Elements", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_L_BRACKET(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "L_BRACKET"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l24;
  yyprintf((stderr, "  ok   %s @ %s\n", "L_BRACKET", ctx->buf+ctx->pos));
  return 1;
  l24:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "L_BRACKET", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Function_Args(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Function_Args"));  if (!yy_Expression(ctx)) goto l25;
  {  int yypos26= ctx->pos, yythunkpos26= ctx->thunkpos;  if (!yy_COMMA(ctx)) goto l26;  if (!yy__(ctx)) goto l26;  if (!yy_Function_Args(ctx)) goto l26;  goto l27;
  l26:;	  ctx->pos= yypos26; ctx->thunkpos= yythunkpos26;
  }
  l27:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Function_Args", ctx->buf+ctx->pos));
  return 1;
  l25:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Function_Args", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Dict(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Dict"));  if (!yy_L_BRACE(ctx)) goto l28;  if (!yy__(ctx)) goto l28;
  {  int yypos29= ctx->pos, yythunkpos29= ctx->thunkpos;  if (!yy_Dict_Elements(ctx)) goto l29;  goto l30;
  l29:;	  ctx->pos= yypos29; ctx->thunkpos= yythunkpos29;
  }
  l30:;	  if (!yy__(ctx)) goto l28;  if (!yy_R_BRACE(ctx)) goto l28;
  yyprintf((stderr, "  ok   %s @ %s\n", "Dict", ctx->buf+ctx->pos));
  return 1;
  l28:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Dict", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Array(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Array"));  if (!yy_L_BRACKET(ctx)) goto l31;  if (!yy__(ctx)) goto l31;
  {  int yypos32= ctx->pos, yythunkpos32= ctx->thunkpos;  if (!yy_Array_Elements(ctx)) goto l32;  goto l33;
  l32:;	  ctx->pos= yypos32; ctx->thunkpos= yythunkpos32;
  }
  l33:;	  if (!yy__(ctx)) goto l31;  if (!yy_R_BRACKET(ctx)) goto l31;
  yyprintf((stderr, "  ok   %s @ %s\n", "Array", ctx->buf+ctx->pos));
  return 1;
  l31:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Array", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_FALSE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "FALSE"));  if (!yymatchClass(ctx, (unsigned char *)"\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l34;
  yyprintf((stderr, "  ok   %s @ %s\n", "FALSE", ctx->buf+ctx->pos));
  return 1;
  l34:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FALSE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_TRUE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "TRUE"));  if (!yymatchClass(ctx, (unsigned char *)"\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l35;
  yyprintf((stderr, "  ok   %s @ %s\n", "TRUE", ctx->buf+ctx->pos));
  return 1;
  l35:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TRUE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_SYMBOL(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "SYMBOL"));  if (!yymatchClass(ctx, (unsigned char *)"\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l36;
  yyprintf((stderr, "  ok   %s @ %s\n", "SYMBOL", ctx->buf+ctx->pos));
  return 1;
  l36:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SYMBOL", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_STRING(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "STRING"));  if (!yymatchClass(ctx, (unsigned char *)"\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING", ctx->buf+ctx->pos));
  return 1;
  l37:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_INTEGER(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "INTEGER"));  if (!yymatchClass(ctx, (unsigned char *)"\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l38;
  yyprintf((stderr, "  ok   %s @ %s\n", "INTEGER", ctx->buf+ctx->pos));
  return 1;
  l38:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "INTEGER", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Function_Call(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Function_Call"));  if (!yy_IDENT(ctx)) goto l39;  if (!yy_L_PAREN(ctx)) goto l39;  if (!yy__(ctx)) goto l39;
  {  int yypos40= ctx->pos, yythunkpos40= ctx->thunkpos;  if (!yy_Function_Args(ctx)) goto l40;  goto l41;
  l40:;	  ctx->pos= yypos40; ctx->thunkpos= yythunkpos40;
  }
  l41:;	  if (!yy__(ctx)) goto l39;  if (!yy_R_PAREN(ctx)) goto l39;
  yyprintf((stderr, "  ok   %s @ %s\n", "Function_Call", ctx->buf+ctx->pos));
  return 1;
  l39:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Function_Call", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Value(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Value"));
  {  int yypos43= ctx->pos, yythunkpos43= ctx->thunkpos;  if (!yy_INTEGER(ctx)) goto l44;  goto l43;
  l44:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yy_STRING(ctx)) goto l45;  goto l43;
  l45:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yy_SYMBOL(ctx)) goto l46;  goto l43;
  l46:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yy_TRUE(ctx)) goto l47;  goto l43;
  l47:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yy_FALSE(ctx)) goto l48;  goto l43;
  l48:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yy_Array(ctx)) goto l49;  goto l43;
  l49:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yy_Dict(ctx)) goto l42;
  }
  l43:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Value", ctx->buf+ctx->pos));
  return 1;
  l42:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Value", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_DIV(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_DIV"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l50;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_DIV", ctx->buf+ctx->pos));
  return 1;
  l50:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_DIV", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_TIMES(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_TIMES"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l51;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_TIMES", ctx->buf+ctx->pos));
  return 1;
  l51:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_TIMES", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Exp3(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Exp3"));
  {  int yypos53= ctx->pos, yythunkpos53= ctx->thunkpos;  if (!yy_Value(ctx)) goto l54;  if (!yy__(ctx)) goto l54;  goto l53;
  l54:;	  ctx->pos= yypos53; ctx->thunkpos= yythunkpos53;  if (!yy_Function_Call(ctx)) goto l55;  if (!yy__(ctx)) goto l55;  goto l53;
  l55:;	  ctx->pos= yypos53; ctx->thunkpos= yythunkpos53;  if (!yy_IDENT(ctx)) goto l56;  if (!yy__(ctx)) goto l56;  goto l53;
  l56:;	  ctx->pos= yypos53; ctx->thunkpos= yythunkpos53;  if (!yy_L_PAREN(ctx)) goto l52;  if (!yy__(ctx)) goto l52;  if (!yy_Expression(ctx)) goto l52;  if (!yy__(ctx)) goto l52;  if (!yy_R_PAREN(ctx)) goto l52;  if (!yy__(ctx)) goto l52;
  }
  l53:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Exp3", ctx->buf+ctx->pos));
  return 1;
  l52:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Exp3", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_MINUS(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_MINUS"));  if (!yymatchClass(ctx, (unsigned char *)"\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l57;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_MINUS", ctx->buf+ctx->pos));
  return 1;
  l57:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_MINUS", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_PLUS(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_PLUS"));  if (!yymatchClass(ctx, (unsigned char *)"\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l58;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_PLUS", ctx->buf+ctx->pos));
  return 1;
  l58:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_PLUS", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Exp2(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Exp2"));  if (!yy_Exp3(ctx)) goto l59;
  l60:;	
  {  int yypos61= ctx->pos, yythunkpos61= ctx->thunkpos;
  {  int yypos62= ctx->pos, yythunkpos62= ctx->thunkpos;  if (!yy_OP_TIMES(ctx)) goto l63;  goto l62;
  l63:;	  ctx->pos= yypos62; ctx->thunkpos= yythunkpos62;  if (!yy_OP_DIV(ctx)) goto l61;
  }
  l62:;	  if (!yy__(ctx)) goto l61;  if (!yy_Exp3(ctx)) goto l61;  goto l60;
  l61:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;
  }  if (!yy__(ctx)) goto l59;
  yyprintf((stderr, "  ok   %s @ %s\n", "Exp2", ctx->buf+ctx->pos));
  return 1;
  l59:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Exp2", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Exp1(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Exp1"));  if (!yy_Exp2(ctx)) goto l64;
  l65:;	
  {  int yypos66= ctx->pos, yythunkpos66= ctx->thunkpos;
  {  int yypos67= ctx->pos, yythunkpos67= ctx->thunkpos;  if (!yy_OP_PLUS(ctx)) goto l68;  goto l67;
  l68:;	  ctx->pos= yypos67; ctx->thunkpos= yythunkpos67;  if (!yy_OP_MINUS(ctx)) goto l66;
  }
  l67:;	  if (!yy__(ctx)) goto l66;  if (!yy_Exp2(ctx)) goto l66;  goto l65;
  l66:;	  ctx->pos= yypos66; ctx->thunkpos= yythunkpos66;
  }  if (!yy__(ctx)) goto l64;
  yyprintf((stderr, "  ok   %s @ %s\n", "Exp1", ctx->buf+ctx->pos));
  return 1;
  l64:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Exp1", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_COMMA(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "COMMA"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l69;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA", ctx->buf+ctx->pos));
  return 1;
  l69:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Parameters(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Parameters"));  if (!yy_IDENT(ctx)) goto l70;  if (!yy__(ctx)) goto l70;
  {  int yypos71= ctx->pos, yythunkpos71= ctx->thunkpos;  if (!yy_COMMA(ctx)) goto l71;  if (!yy__(ctx)) goto l71;  if (!yy_Parameters(ctx)) goto l71;  goto l72;
  l71:;	  ctx->pos= yypos71; ctx->thunkpos= yythunkpos71;
  }
  l72:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Parameters", ctx->buf+ctx->pos));
  return 1;
  l70:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Parameters", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_R_PAREN(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "R_PAREN"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l73;
  yyprintf((stderr, "  ok   %s @ %s\n", "R_PAREN", ctx->buf+ctx->pos));
  return 1;
  l73:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "R_PAREN", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Parameter_List(yycontext *ctx)
{
  yyprintf((stderr, "%s\n", "Parameter_List"));
  {  int yypos75= ctx->pos, yythunkpos75= ctx->thunkpos;  if (!yy_Parameters(ctx)) goto l75;  goto l76;
  l75:;	  ctx->pos= yypos75; ctx->thunkpos= yythunkpos75;
  }
  l76:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Parameter_List", ctx->buf+ctx->pos));
  return 1;
}
YY_RULE(int) yy_L_PAREN(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "L_PAREN"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l77;
  yyprintf((stderr, "  ok   %s @ %s\n", "L_PAREN", ctx->buf+ctx->pos));
  return 1;
  l77:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "L_PAREN", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_DEF(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "DEF"));  if (!yymatchClass(ctx, (unsigned char *)"\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l78;
  yyprintf((stderr, "  ok   %s @ %s\n", "DEF", ctx->buf+ctx->pos));
  return 1;
  l78:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DEF", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_RETURN(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "RETURN"));  if (!yymatchClass(ctx, (unsigned char *)"\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l79;
  yyprintf((stderr, "  ok   %s @ %s\n", "RETURN", ctx->buf+ctx->pos));
  return 1;
  l79:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RETURN", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OP_ASSIGN(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OP_ASSIGN"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l80;
  yyprintf((stderr, "  ok   %s @ %s\n", "OP_ASSIGN", ctx->buf+ctx->pos));
  return 1;
  l80:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OP_ASSIGN", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_IDENT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IDENT"));  if (!yymatchClass(ctx, (unsigned char *)"\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l81;
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT", ctx->buf+ctx->pos));
  return 1;
  l81:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_PASS(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "PASS"));  if (!yymatchClass(ctx, (unsigned char *)"\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l82;
  yyprintf((stderr, "  ok   %s @ %s\n", "PASS", ctx->buf+ctx->pos));
  return 1;
  l82:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PASS", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_WHILE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "WHILE"));  if (!yymatchClass(ctx, (unsigned char *)"\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l83;
  yyprintf((stderr, "  ok   %s @ %s\n", "WHILE", ctx->buf+ctx->pos));
  return 1;
  l83:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WHILE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_ELSE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "ELSE"));  if (!yymatchClass(ctx, (unsigned char *)"\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l84;
  yyprintf((stderr, "  ok   %s @ %s\n", "ELSE", ctx->buf+ctx->pos));
  return 1;
  l84:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ELSE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_ELSEIF(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "ELSEIF"));  if (!yymatchClass(ctx, (unsigned char *)"\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l85;
  yyprintf((stderr, "  ok   %s @ %s\n", "ELSEIF", ctx->buf+ctx->pos));
  return 1;
  l85:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ELSEIF", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Block_Prelude(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Block_Prelude"));  if (!yy__(ctx)) goto l86;  if (!yy_COLON(ctx)) goto l86;  if (!yy__(ctx)) goto l86;  if (!yy_EOL(ctx)) goto l86;
  yyprintf((stderr, "  ok   %s @ %s\n", "Block_Prelude", ctx->buf+ctx->pos));
  return 1;
  l86:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Block_Prelude", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Expression(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Expression"));  if (!yy_Exp1(ctx)) goto l87;
  yyprintf((stderr, "  ok   %s @ %s\n", "Expression", ctx->buf+ctx->pos));
  return 1;
  l87:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Expression", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *ctx)
{
  yyprintf((stderr, "%s\n", "_"));
  l89:;	
  {  int yypos90= ctx->pos, yythunkpos90= ctx->thunkpos;  if (!yy_WHITESPACE(ctx)) goto l90;  goto l89;
  l90:;	  ctx->pos= yypos90; ctx->thunkpos= yythunkpos90;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", ctx->buf+ctx->pos));
  return 1;
}
YY_RULE(int) yy_IF(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IF"));  if (!yymatchClass(ctx, (unsigned char *)"\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l91;
  yyprintf((stderr, "  ok   %s @ %s\n", "IF", ctx->buf+ctx->pos));
  return 1;
  l91:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IF", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Else_Part(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Else_Part"));  if (!yy_ELSE(ctx)) goto l92;  if (!yy_Block_Prelude(ctx)) goto l92;  if (!yy_Statement_Block(ctx)) goto l92;
  yyprintf((stderr, "  ok   %s @ %s\n", "Else_Part", ctx->buf+ctx->pos));
  return 1;
  l92:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Else_Part", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Elseif_Part(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Elseif_Part"));  if (!yy_ELSEIF(ctx)) goto l93;  if (!yy__(ctx)) goto l93;  if (!yy_Expression(ctx)) goto l93;  if (!yy_Block_Prelude(ctx)) goto l93;  if (!yy_Statement_Block(ctx)) goto l93;
  yyprintf((stderr, "  ok   %s @ %s\n", "Elseif_Part", ctx->buf+ctx->pos));
  return 1;
  l93:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Elseif_Part", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_If_Part(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "If_Part"));  if (!yy_IF(ctx)) goto l94;  if (!yy__(ctx)) goto l94;  if (!yy_Expression(ctx)) goto l94;  if (!yy_Block_Prelude(ctx)) goto l94;  if (!yy_Statement_Block(ctx)) goto l94;
  yyprintf((stderr, "  ok   %s @ %s\n", "If_Part", ctx->buf+ctx->pos));
  return 1;
  l94:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "If_Part", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Named_Function_Def(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Named_Function_Def"));  if (!yy_DEF(ctx)) goto l95;  if (!yy__(ctx)) goto l95;  if (!yy_IDENT(ctx)) goto l95;  if (!yy_L_PAREN(ctx)) goto l95;  if (!yy__(ctx)) goto l95;  if (!yy_Parameter_List(ctx)) goto l95;  if (!yy__(ctx)) goto l95;  if (!yy_R_PAREN(ctx)) goto l95;  if (!yy_Block_Prelude(ctx)) goto l95;  if (!yy_Statement_Block(ctx)) goto l95;
  yyprintf((stderr, "  ok   %s @ %s\n", "Named_Function_Def", ctx->buf+ctx->pos));
  return 1;
  l95:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Named_Function_Def", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Return_Statement(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Return_Statement"));  if (!yy_RETURN(ctx)) goto l96;  if (!yy__(ctx)) goto l96;
  {  int yypos97= ctx->pos, yythunkpos97= ctx->thunkpos;  if (!yy_Expression(ctx)) goto l97;  goto l98;
  l97:;	  ctx->pos= yypos97; ctx->thunkpos= yythunkpos97;
  }
  l98:;	  if (!yy_EOL(ctx)) goto l96;
  yyprintf((stderr, "  ok   %s @ %s\n", "Return_Statement", ctx->buf+ctx->pos));
  return 1;
  l96:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Return_Statement", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Expression_Statement(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Expression_Statement"));  if (!yy_Expression(ctx)) goto l99;  if (!yy__(ctx)) goto l99;  if (!yy_EOL(ctx)) goto l99;
  yyprintf((stderr, "  ok   %s @ %s\n", "Expression_Statement", ctx->buf+ctx->pos));
  return 1;
  l99:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Expression_Statement", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Assign_Statement(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Assign_Statement"));  if (!yy_IDENT(ctx)) goto l100;  if (!yy__(ctx)) goto l100;  if (!yy_OP_ASSIGN(ctx)) goto l100;  if (!yy__(ctx)) goto l100;  if (!yy_Expression(ctx)) goto l100;  if (!yy__(ctx)) goto l100;  if (!yy_EOL(ctx)) goto l100;
  yyprintf((stderr, "  ok   %s @ %s\n", "Assign_Statement", ctx->buf+ctx->pos));
  return 1;
  l100:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Assign_Statement", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Pass_Statement(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Pass_Statement"));  if (!yy_PASS(ctx)) goto l101;  if (!yy__(ctx)) goto l101;  if (!yy_EOL(ctx)) goto l101;
  yyprintf((stderr, "  ok   %s @ %s\n", "Pass_Statement", ctx->buf+ctx->pos));
  return 1;
  l101:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Pass_Statement", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_While_Statement(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "While_Statement"));  if (!yy_WHILE(ctx)) goto l102;  if (!yy__(ctx)) goto l102;  if (!yy_Expression(ctx)) goto l102;  if (!yy_Block_Prelude(ctx)) goto l102;  if (!yy_Statement_Block(ctx)) goto l102;
  yyprintf((stderr, "  ok   %s @ %s\n", "While_Statement", ctx->buf+ctx->pos));
  return 1;
  l102:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "While_Statement", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_If_Statement(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "If_Statement"));  if (!yy_If_Part(ctx)) goto l103;
  l104:;	
  {  int yypos105= ctx->pos, yythunkpos105= ctx->thunkpos;  if (!yy_Elseif_Part(ctx)) goto l105;  goto l104;
  l105:;	  ctx->pos= yypos105; ctx->thunkpos= yythunkpos105;
  }
  {  int yypos106= ctx->pos, yythunkpos106= ctx->thunkpos;  if (!yy_Else_Part(ctx)) goto l106;  goto l107;
  l106:;	  ctx->pos= yypos106; ctx->thunkpos= yythunkpos106;
  }
  l107:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "If_Statement", ctx->buf+ctx->pos));
  return 1;
  l103:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "If_Statement", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OUTDENT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OUTDENT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l108;
  yyprintf((stderr, "  ok   %s @ %s\n", "OUTDENT", ctx->buf+ctx->pos));
  return 1;
  l108:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OUTDENT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Statement(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Statement"));
  {  int yypos110= ctx->pos, yythunkpos110= ctx->thunkpos;  if (!yy_If_Statement(ctx)) goto l111;  goto l110;
  l111:;	  ctx->pos= yypos110; ctx->thunkpos= yythunkpos110;  if (!yy_While_Statement(ctx)) goto l112;  goto l110;
  l112:;	  ctx->pos= yypos110; ctx->thunkpos= yythunkpos110;  if (!yy_Pass_Statement(ctx)) goto l113;  goto l110;
  l113:;	  ctx->pos= yypos110; ctx->thunkpos= yythunkpos110;  if (!yy_Assign_Statement(ctx)) goto l114;  goto l110;
  l114:;	  ctx->pos= yypos110; ctx->thunkpos= yythunkpos110;  if (!yy_Expression_Statement(ctx)) goto l115;  goto l110;
  l115:;	  ctx->pos= yypos110; ctx->thunkpos= yythunkpos110;  if (!yy_Return_Statement(ctx)) goto l116;  goto l110;
  l116:;	  ctx->pos= yypos110; ctx->thunkpos= yythunkpos110;  if (!yy_Named_Function_Def(ctx)) goto l109;
  }
  l110:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Statement", ctx->buf+ctx->pos));
  return 1;
  l109:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Statement", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_EOL(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l117;
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", ctx->buf+ctx->pos));
  return 1;
  l117:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_INDENT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "INDENT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l118;
  yyprintf((stderr, "  ok   %s @ %s\n", "INDENT", ctx->buf+ctx->pos));
  return 1;
  l118:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "INDENT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Statement_Block(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Statement_Block"));  if (!yy_INDENT(ctx)) goto l119;
  l120:;	
  {  int yypos121= ctx->pos, yythunkpos121= ctx->thunkpos;  if (!yy_EOL(ctx)) goto l121;  goto l120;
  l121:;	  ctx->pos= yypos121; ctx->thunkpos= yythunkpos121;
  }  if (!yy_Statement(ctx)) goto l119;
  l124:;	
  {  int yypos125= ctx->pos, yythunkpos125= ctx->thunkpos;  if (!yy_EOL(ctx)) goto l125;  goto l124;
  l125:;	  ctx->pos= yypos125; ctx->thunkpos= yythunkpos125;
  }
  l122:;	
  {  int yypos123= ctx->pos, yythunkpos123= ctx->thunkpos;  if (!yy_Statement(ctx)) goto l123;
  l126:;	
  {  int yypos127= ctx->pos, yythunkpos127= ctx->thunkpos;  if (!yy_EOL(ctx)) goto l127;  goto l126;
  l127:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;
  }  goto l122;
  l123:;	  ctx->pos= yypos123; ctx->thunkpos= yythunkpos123;
  }  if (!yy_OUTDENT(ctx)) goto l119;
  yyprintf((stderr, "  ok   %s @ %s\n", "Statement_Block", ctx->buf+ctx->pos));
  return 1;
  l119:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Statement_Block", ctx->buf+ctx->pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *ctx);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->buflen)
    {
      yyctx->buflen= 1024;
      yyctx->buf= (char *)malloc(yyctx->buflen);
      yyctx->textlen= 1024;
      yyctx->text= (char *)malloc(yyctx->textlen);
      yyctx->thunkslen= 32;
      yyctx->thunks= (yythunk *)malloc(sizeof(yythunk) * yyctx->thunkslen);
      yyctx->valslen= 32;
      yyctx->vals= (YYSTYPE *)malloc(sizeof(YYSTYPE) * yyctx->valslen);
      yyctx->begin= yyctx->end= yyctx->pos= yyctx->limit= yyctx->thunkpos= 0;
    }
  yyctx->begin= yyctx->end= yyctx->pos;
  yyctx->thunkpos= 0;
  yyctx->val= yyctx->vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_Statement_Block);
}

#endif


parser_t *parser_create(context_t *c, scanner_t *s) {
    yycontext *parser = malloc(sizeof(yycontext));
    memset(parser, 0, sizeof(yycontext));
    parser->scanner = s;
    parser->context = c;
    return (parser_t*)parser;
}

ast_id_t parser_parse(parser_t *p) {
    if (!yyparse((yycontext*)p)) {
        return 0;
    } else {
        return 1;
        return ((yycontext*)p)->yy;
    }
}

