/* A recursive-descent parser generated by peg 0.1.9 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 19

#include "menace/scanner.h"
#include <stdio.h>

#define YY_INPUT(buf, result, max_size)             \
{                                                   \
    int yyc = getc(ctx->file);                      \
    result = (EOF == yyc) ? 0 : (*(buf)=yyc, 1);    \
}

#define YY_CTX_LOCAL
#define YYSTYPE             token_t
#define YY_PARSE(T)         static T
#define MAX_INDENT          32
#define CURRENT_INDENT      (ctx->indents[ctx->indent_depth])

#define YY_CTX_MEMBERS                                  \
    FILE                *file;                          \
    int                 indent_depth;                   \
    int                 indents[MAX_INDENT];            \
    int                 pending_dents;                  \
    int                 pending_is_indent;              \
    token_t             pushback_token;                 \
    char                is_eof;                         \
    char                was_newline;                    \
    char                *error;

#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( ctx->begin= ctx->pos, 1)
#endif
#ifndef YY_END
#define YY_END		( ctx->end= ctx->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *ctx, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *buf;
  int       buflen;
  int       pos;
  int       limit;
  char     *text;
  int       textlen;
  int       begin;
  int       end;
  int       textmax;
  yythunk  *thunks;
  int       thunkslen;
  int       thunkpos;
  YYSTYPE   yy;
  YYSTYPE  *val;
  YYSTYPE  *vals;
  int       valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext yyctx0;
yycontext *yyctx= &yyctx0;
#endif

YY_LOCAL(int) yyrefill(yycontext *ctx)
{
  int yyn;
  while (ctx->buflen - ctx->pos < 512)
    {
      ctx->buflen *= 2;
      ctx->buf= (char *)realloc(ctx->buf, ctx->buflen);
    }
  YY_INPUT((ctx->buf + ctx->pos), yyn, (ctx->buflen - ctx->pos));
  if (!yyn) return 0;
  ctx->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *ctx)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  ++ctx->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *ctx, int c)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  if ((unsigned char)ctx->buf[ctx->pos] == c)
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchChar(ctx, %c) @ %s\n", c, ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(ctx, %c) @ %s\n", c, ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *ctx, char *s)
{
  int yysav= ctx->pos;
  while (*s)
    {
      if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
      if (ctx->buf[ctx->pos] != *s)
        {
          ctx->pos= yysav;
          return 0;
        }
      ++s;
      ++ctx->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *ctx, unsigned char *bits)
{
  int c;
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  c= (unsigned char)ctx->buf[ctx->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *ctx, yyaction action, int begin, int end)
{
  while (ctx->thunkpos >= ctx->thunkslen)
    {
      ctx->thunkslen *= 2;
      ctx->thunks= (yythunk *)realloc(ctx->thunks, sizeof(yythunk) * ctx->thunkslen);
    }
  ctx->thunks[ctx->thunkpos].begin=  begin;
  ctx->thunks[ctx->thunkpos].end=    end;
  ctx->thunks[ctx->thunkpos].action= action;
  ++ctx->thunkpos;
}

YY_LOCAL(int) yyText(yycontext *ctx, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (ctx->textlen < (yyleng + 1))
	{
	  ctx->textlen *= 2;
	  ctx->text= (char *)realloc(ctx->text, ctx->textlen);
	}
      memcpy(ctx->text, ctx->buf + begin, yyleng);
    }
  ctx->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *ctx)
{
  int pos;
  for (pos= 0;  pos < ctx->thunkpos;  ++pos)
    {
      yythunk *thunk= &ctx->thunks[pos];
      int yyleng= thunk->end ? yyText(ctx, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, ctx->text));
      thunk->action(ctx, ctx->text, yyleng);
    }
  ctx->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *ctx)
{
  if ((ctx->limit -= ctx->pos))
    {
      memmove(ctx->buf, ctx->buf + ctx->pos, ctx->limit);
    }
  ctx->begin -= ctx->pos;
  ctx->end -= ctx->pos;
  ctx->pos= ctx->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *ctx, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(ctx);
      yyCommit(ctx);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *ctx, char *text, int count)  { ctx->val += count; }
YY_LOCAL(void) yyPop(yycontext *ctx, char *text, int count)   { ctx->val -= count; }
YY_LOCAL(void) yySet(yycontext *ctx, char *text, int count)   { ctx->val[count]= ctx->yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(ctx, yythunkpos0)

YY_RULE(int) yy_ESCAPE(yycontext *ctx); /* 19 */
YY_RULE(int) yy_NON_PRINTABLE(yycontext *ctx); /* 18 */
YY_RULE(int) yy_IDENT_TAIL(yycontext *ctx); /* 17 */
YY_RULE(int) yy_IDENT_REST(yycontext *ctx); /* 16 */
YY_RULE(int) yy_IDENT_START(yycontext *ctx); /* 15 */
YY_RULE(int) yy_STRING_CHAR(yycontext *ctx); /* 14 */
YY_RULE(int) yy_BIN_DIGIT(yycontext *ctx); /* 13 */
YY_RULE(int) yy_OCT_DIGIT(yycontext *ctx); /* 12 */
YY_RULE(int) yy_HEX_DIGIT(yycontext *ctx); /* 11 */
YY_RULE(int) yy_EOF(yycontext *ctx); /* 10 */
YY_RULE(int) yy_EOL(yycontext *ctx); /* 9 */
YY_RULE(int) yy_WHITESPACE(yycontext *ctx); /* 8 */
YY_RULE(int) yy_IDENT(yycontext *ctx); /* 7 */
YY_RULE(int) yy_SYMBOL(yycontext *ctx); /* 6 */
YY_RULE(int) yy_Keyword(yycontext *ctx); /* 5 */
YY_RULE(int) yy_Punctuation(yycontext *ctx); /* 4 */
YY_RULE(int) yy_STRING(yycontext *ctx); /* 3 */
YY_RULE(int) yy_INTEGER(yycontext *ctx); /* 2 */
YY_RULE(int) yy_Token(yycontext *ctx); /* 1 */

YY_ACTION(void) yy_14_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_14_Keyword\n"));
   yy = T_IN ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_13_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_13_Keyword\n"));
   yy = T_FOR ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_12_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_12_Keyword\n"));
   yy = T_NOT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_11_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_11_Keyword\n"));
   yy = T_OR ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_10_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_10_Keyword\n"));
   yy = T_AND ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_9_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_9_Keyword\n"));
   yy = T_RETURN ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_8_Keyword\n"));
   yy = T_PASS ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_7_Keyword\n"));
   yy = T_FALSE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_6_Keyword\n"));
   yy = T_TRUE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_5_Keyword\n"));
   yy = T_ELSE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_4_Keyword\n"));
   yy = T_ELSEIF ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_3_Keyword\n"));
   yy = T_IF ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_2_Keyword\n"));
   yy = T_WHILE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_Keyword\n"));
   yy = T_DEF ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_30_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_30_Punctuation\n"));
   yy = T_R_BRACKET ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_29_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_29_Punctuation\n"));
   yy = T_L_BRACKET ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_28_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_28_Punctuation\n"));
   yy = T_R_BRACE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_27_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_27_Punctuation\n"));
   yy = T_L_BRACE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_26_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_26_Punctuation\n"));
   yy = T_R_PAREN ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_25_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_25_Punctuation\n"));
   yy = T_L_PAREN ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_24_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_24_Punctuation\n"));
   yy = T_DOT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_23_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_23_Punctuation\n"));
   yy = T_COMMA ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_22_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_22_Punctuation\n"));
   yy = T_COLON ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_21_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_21_Punctuation\n"));
   yy = T_HASHROCKET ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_20_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_20_Punctuation\n"));
   yy = T_EQUALS ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_19_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_19_Punctuation\n"));
   yy = T_GT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_18_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_18_Punctuation\n"));
   yy = T_GTE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_17_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_17_Punctuation\n"));
   yy = T_LTE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_16_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_16_Punctuation\n"));
   yy = T_LT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_15_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_15_Punctuation\n"));
   yy = T_NEQ ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_14_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_14_Punctuation\n"));
   yy = T_EQ ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_13_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_13_Punctuation\n"));
   yy = T_DBL_PIPE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_12_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_12_Punctuation\n"));
   yy = T_DBL_AMPERSAND ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_11_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_11_Punctuation\n"));
   yy = T_PIPE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_10_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_10_Punctuation\n"));
   yy = T_AMPERSAND ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_9_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_9_Punctuation\n"));
   yy = T_BANG ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_8_Punctuation\n"));
   yy = T_HAT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_7_Punctuation\n"));
   yy = T_TILDE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_6_Punctuation\n"));
   yy = T_POW ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_5_Punctuation\n"));
   yy = T_MOD ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_4_Punctuation\n"));
   yy = T_DIV ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_3_Punctuation\n"));
   yy = T_TIMES ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_2_Punctuation\n"));
   yy = T_MINUS ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_Punctuation\n"));
   yy = T_PLUS ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_7_Token\n"));
   yy = T_EOF ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_6_Token\n"));
   yy = T_EOL ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_5_Token\n"));
   yy = T_WHITESPACE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_4_Token\n"));
   yy = T_IDENT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_3_Token\n"));
   yy = T_SYMBOL ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_2_Token\n"));
   yy = T_STRING ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_Token\n"));
   yy = T_INTEGER ;
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_ESCAPE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "ESCAPE"));  if (!yymatchChar(ctx, '\\')) goto l1;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\204\000\000\000\000\000\000\020\104\100\024\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "ESCAPE", ctx->buf+ctx->pos));
  return 1;
  l1:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ESCAPE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_NON_PRINTABLE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "NON_PRINTABLE"));
  {  int yypos3= ctx->pos, yythunkpos3= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\377\377\377\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;  goto l3;
  l4:;	  ctx->pos= yypos3; ctx->thunkpos= yythunkpos3;  if (!yymatchString(ctx, "\177")) goto l2;
  }
  l3:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NON_PRINTABLE", ctx->buf+ctx->pos));
  return 1;
  l2:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NON_PRINTABLE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_IDENT_TAIL(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IDENT_TAIL"));
  {  int yypos6= ctx->pos, yythunkpos6= ctx->thunkpos;  if (!yymatchChar(ctx, '!')) goto l7;  goto l6;
  l7:;	  ctx->pos= yypos6; ctx->thunkpos= yythunkpos6;  if (!yymatchChar(ctx, '?')) goto l5;
  }
  l6:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT_TAIL", ctx->buf+ctx->pos));
  return 1;
  l5:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT_TAIL", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_IDENT_REST(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IDENT_REST"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT_REST", ctx->buf+ctx->pos));
  return 1;
  l8:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT_REST", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_IDENT_START(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IDENT_START"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT_START", ctx->buf+ctx->pos));
  return 1;
  l9:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT_START", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_STRING_CHAR(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "STRING_CHAR"));
  {  int yypos11= ctx->pos, yythunkpos11= ctx->thunkpos;  if (!yy_ESCAPE(ctx)) goto l12;  goto l11;
  l12:;	  ctx->pos= yypos11; ctx->thunkpos= yythunkpos11;
  {  int yypos13= ctx->pos, yythunkpos13= ctx->thunkpos;  if (!yymatchChar(ctx, '\\')) goto l13;  goto l10;
  l13:;	  ctx->pos= yypos13; ctx->thunkpos= yythunkpos13;
  }
  {  int yypos14= ctx->pos, yythunkpos14= ctx->thunkpos;  if (!yymatchChar(ctx, '"')) goto l14;  goto l10;
  l14:;	  ctx->pos= yypos14; ctx->thunkpos= yythunkpos14;
  }
  {  int yypos15= ctx->pos, yythunkpos15= ctx->thunkpos;  if (!yy_NON_PRINTABLE(ctx)) goto l15;  goto l10;
  l15:;	  ctx->pos= yypos15; ctx->thunkpos= yythunkpos15;
  }  if (!yymatchDot(ctx)) goto l10;
  }
  l11:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING_CHAR", ctx->buf+ctx->pos));
  return 1;
  l10:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING_CHAR", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_BIN_DIGIT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "BIN_DIGIT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l16;
  yyprintf((stderr, "  ok   %s @ %s\n", "BIN_DIGIT", ctx->buf+ctx->pos));
  return 1;
  l16:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BIN_DIGIT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OCT_DIGIT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OCT_DIGIT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l17;
  yyprintf((stderr, "  ok   %s @ %s\n", "OCT_DIGIT", ctx->buf+ctx->pos));
  return 1;
  l17:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OCT_DIGIT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_HEX_DIGIT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "HEX_DIGIT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l18;
  yyprintf((stderr, "  ok   %s @ %s\n", "HEX_DIGIT", ctx->buf+ctx->pos));
  return 1;
  l18:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "HEX_DIGIT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos20= ctx->pos, yythunkpos20= ctx->thunkpos;  if (!yymatchDot(ctx)) goto l20;  goto l19;
  l20:;	  ctx->pos= yypos20; ctx->thunkpos= yythunkpos20;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", ctx->buf+ctx->pos));
  return 1;
  l19:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_EOL(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos22= ctx->pos, yythunkpos22= ctx->thunkpos;  if (!yymatchString(ctx, "\r\n")) goto l23;  goto l22;
  l23:;	  ctx->pos= yypos22; ctx->thunkpos= yythunkpos22;  if (!yymatchChar(ctx, '\n')) goto l24;  goto l22;
  l24:;	  ctx->pos= yypos22; ctx->thunkpos= yythunkpos22;  if (!yymatchChar(ctx, '\r')) goto l21;
  }
  l22:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", ctx->buf+ctx->pos));
  return 1;
  l21:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_WHITESPACE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "WHITESPACE"));  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l25;
  {  int yypos28= ctx->pos, yythunkpos28= ctx->thunkpos;  if (!yymatchChar(ctx, ' ')) goto l29;  goto l28;
  l29:;	  ctx->pos= yypos28; ctx->thunkpos= yythunkpos28;  if (!yymatchChar(ctx, '\t')) goto l25;
  }
  l28:;	
  l26:;	
  {  int yypos27= ctx->pos, yythunkpos27= ctx->thunkpos;
  {  int yypos30= ctx->pos, yythunkpos30= ctx->thunkpos;  if (!yymatchChar(ctx, ' ')) goto l31;  goto l30;
  l31:;	  ctx->pos= yypos30; ctx->thunkpos= yythunkpos30;  if (!yymatchChar(ctx, '\t')) goto l27;
  }
  l30:;	  goto l26;
  l27:;	  ctx->pos= yypos27; ctx->thunkpos= yythunkpos27;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l25;
  yyprintf((stderr, "  ok   %s @ %s\n", "WHITESPACE", ctx->buf+ctx->pos));
  return 1;
  l25:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WHITESPACE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_IDENT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IDENT"));  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l32;  if (!yy_IDENT_START(ctx)) goto l32;
  l33:;	
  {  int yypos34= ctx->pos, yythunkpos34= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l34;  goto l33;
  l34:;	  ctx->pos= yypos34; ctx->thunkpos= yythunkpos34;
  }
  {  int yypos35= ctx->pos, yythunkpos35= ctx->thunkpos;  if (!yy_IDENT_TAIL(ctx)) goto l35;  goto l36;
  l35:;	  ctx->pos= yypos35; ctx->thunkpos= yythunkpos35;
  }
  l36:;	  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l32;
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT", ctx->buf+ctx->pos));
  return 1;
  l32:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_SYMBOL(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "SYMBOL"));  if (!yymatchChar(ctx, ':')) goto l37;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l37;  if (!yy_IDENT_START(ctx)) goto l37;
  l38:;	
  {  int yypos39= ctx->pos, yythunkpos39= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l39;  goto l38;
  l39:;	  ctx->pos= yypos39; ctx->thunkpos= yythunkpos39;
  }
  {  int yypos40= ctx->pos, yythunkpos40= ctx->thunkpos;  if (!yy_IDENT_TAIL(ctx)) goto l40;  goto l41;
  l40:;	  ctx->pos= yypos40; ctx->thunkpos= yythunkpos40;
  }
  l41:;	  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "SYMBOL", ctx->buf+ctx->pos));
  return 1;
  l37:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SYMBOL", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Keyword(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Keyword"));
  {  int yypos43= ctx->pos, yythunkpos43= ctx->thunkpos;  if (!yymatchString(ctx, "def")) goto l44;
  {  int yypos45= ctx->pos, yythunkpos45= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l45;  goto l44;
  l45:;	  ctx->pos= yypos45; ctx->thunkpos= yythunkpos45;
  }  yyDo(ctx, yy_1_Keyword, ctx->begin, ctx->end);  goto l43;
  l44:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "while")) goto l46;
  {  int yypos47= ctx->pos, yythunkpos47= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l47;  goto l46;
  l47:;	  ctx->pos= yypos47; ctx->thunkpos= yythunkpos47;
  }  yyDo(ctx, yy_2_Keyword, ctx->begin, ctx->end);  goto l43;
  l46:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "if")) goto l48;
  {  int yypos49= ctx->pos, yythunkpos49= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l49;  goto l48;
  l49:;	  ctx->pos= yypos49; ctx->thunkpos= yythunkpos49;
  }  yyDo(ctx, yy_3_Keyword, ctx->begin, ctx->end);  goto l43;
  l48:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "elseif")) goto l50;
  {  int yypos51= ctx->pos, yythunkpos51= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l51;  goto l50;
  l51:;	  ctx->pos= yypos51; ctx->thunkpos= yythunkpos51;
  }  yyDo(ctx, yy_4_Keyword, ctx->begin, ctx->end);  goto l43;
  l50:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "else")) goto l52;
  {  int yypos53= ctx->pos, yythunkpos53= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l53;  goto l52;
  l53:;	  ctx->pos= yypos53; ctx->thunkpos= yythunkpos53;
  }  yyDo(ctx, yy_5_Keyword, ctx->begin, ctx->end);  goto l43;
  l52:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "true")) goto l54;
  {  int yypos55= ctx->pos, yythunkpos55= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l55;  goto l54;
  l55:;	  ctx->pos= yypos55; ctx->thunkpos= yythunkpos55;
  }  yyDo(ctx, yy_6_Keyword, ctx->begin, ctx->end);  goto l43;
  l54:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "false")) goto l56;
  {  int yypos57= ctx->pos, yythunkpos57= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l57;  goto l56;
  l57:;	  ctx->pos= yypos57; ctx->thunkpos= yythunkpos57;
  }  yyDo(ctx, yy_7_Keyword, ctx->begin, ctx->end);  goto l43;
  l56:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "pass")) goto l58;
  {  int yypos59= ctx->pos, yythunkpos59= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l59;  goto l58;
  l59:;	  ctx->pos= yypos59; ctx->thunkpos= yythunkpos59;
  }  yyDo(ctx, yy_8_Keyword, ctx->begin, ctx->end);  goto l43;
  l58:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "return")) goto l60;
  {  int yypos61= ctx->pos, yythunkpos61= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l61;  goto l60;
  l61:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;
  }  yyDo(ctx, yy_9_Keyword, ctx->begin, ctx->end);  goto l43;
  l60:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "and")) goto l62;
  {  int yypos63= ctx->pos, yythunkpos63= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l63;  goto l62;
  l63:;	  ctx->pos= yypos63; ctx->thunkpos= yythunkpos63;
  }  yyDo(ctx, yy_10_Keyword, ctx->begin, ctx->end);  goto l43;
  l62:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "or")) goto l64;
  {  int yypos65= ctx->pos, yythunkpos65= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l65;  goto l64;
  l65:;	  ctx->pos= yypos65; ctx->thunkpos= yythunkpos65;
  }  yyDo(ctx, yy_11_Keyword, ctx->begin, ctx->end);  goto l43;
  l64:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "not")) goto l66;
  {  int yypos67= ctx->pos, yythunkpos67= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l67;  goto l66;
  l67:;	  ctx->pos= yypos67; ctx->thunkpos= yythunkpos67;
  }  yyDo(ctx, yy_12_Keyword, ctx->begin, ctx->end);  goto l43;
  l66:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "for")) goto l68;
  {  int yypos69= ctx->pos, yythunkpos69= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l69;  goto l68;
  l69:;	  ctx->pos= yypos69; ctx->thunkpos= yythunkpos69;
  }  yyDo(ctx, yy_13_Keyword, ctx->begin, ctx->end);  goto l43;
  l68:;	  ctx->pos= yypos43; ctx->thunkpos= yythunkpos43;  if (!yymatchString(ctx, "in")) goto l42;
  {  int yypos70= ctx->pos, yythunkpos70= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l70;  goto l42;
  l70:;	  ctx->pos= yypos70; ctx->thunkpos= yythunkpos70;
  }  yyDo(ctx, yy_14_Keyword, ctx->begin, ctx->end);
  }
  l43:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Keyword", ctx->buf+ctx->pos));
  return 1;
  l42:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Keyword", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Punctuation(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Punctuation"));
  {  int yypos72= ctx->pos, yythunkpos72= ctx->thunkpos;  if (!yymatchChar(ctx, '+')) goto l73;  yyDo(ctx, yy_1_Punctuation, ctx->begin, ctx->end);  goto l72;
  l73:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '-')) goto l74;  yyDo(ctx, yy_2_Punctuation, ctx->begin, ctx->end);  goto l72;
  l74:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '*')) goto l75;
  {  int yypos76= ctx->pos, yythunkpos76= ctx->thunkpos;  if (!yymatchChar(ctx, '*')) goto l76;  goto l75;
  l76:;	  ctx->pos= yypos76; ctx->thunkpos= yythunkpos76;
  }  yyDo(ctx, yy_3_Punctuation, ctx->begin, ctx->end);  goto l72;
  l75:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '/')) goto l77;  yyDo(ctx, yy_4_Punctuation, ctx->begin, ctx->end);  goto l72;
  l77:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '%')) goto l78;  yyDo(ctx, yy_5_Punctuation, ctx->begin, ctx->end);  goto l72;
  l78:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchString(ctx, "**")) goto l79;  yyDo(ctx, yy_6_Punctuation, ctx->begin, ctx->end);  goto l72;
  l79:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '~')) goto l80;  yyDo(ctx, yy_7_Punctuation, ctx->begin, ctx->end);  goto l72;
  l80:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '^')) goto l81;  yyDo(ctx, yy_8_Punctuation, ctx->begin, ctx->end);  goto l72;
  l81:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '!')) goto l82;
  {  int yypos83= ctx->pos, yythunkpos83= ctx->thunkpos;  if (!yymatchChar(ctx, '=')) goto l83;  goto l82;
  l83:;	  ctx->pos= yypos83; ctx->thunkpos= yythunkpos83;
  }  yyDo(ctx, yy_9_Punctuation, ctx->begin, ctx->end);  goto l72;
  l82:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '&')) goto l84;
  {  int yypos85= ctx->pos, yythunkpos85= ctx->thunkpos;  if (!yymatchChar(ctx, '&')) goto l85;  goto l84;
  l85:;	  ctx->pos= yypos85; ctx->thunkpos= yythunkpos85;
  }  yyDo(ctx, yy_10_Punctuation, ctx->begin, ctx->end);  goto l72;
  l84:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '|')) goto l86;
  {  int yypos87= ctx->pos, yythunkpos87= ctx->thunkpos;  if (!yymatchChar(ctx, '|')) goto l87;  goto l86;
  l87:;	  ctx->pos= yypos87; ctx->thunkpos= yythunkpos87;
  }  yyDo(ctx, yy_11_Punctuation, ctx->begin, ctx->end);  goto l72;
  l86:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchString(ctx, "&&")) goto l88;  yyDo(ctx, yy_12_Punctuation, ctx->begin, ctx->end);  goto l72;
  l88:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchString(ctx, "||")) goto l89;  yyDo(ctx, yy_13_Punctuation, ctx->begin, ctx->end);  goto l72;
  l89:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchString(ctx, "==")) goto l90;  yyDo(ctx, yy_14_Punctuation, ctx->begin, ctx->end);  goto l72;
  l90:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchString(ctx, "!=")) goto l91;  yyDo(ctx, yy_15_Punctuation, ctx->begin, ctx->end);  goto l72;
  l91:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '<')) goto l92;  yyDo(ctx, yy_16_Punctuation, ctx->begin, ctx->end);  goto l72;
  l92:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchString(ctx, "<=")) goto l93;  yyDo(ctx, yy_17_Punctuation, ctx->begin, ctx->end);  goto l72;
  l93:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchString(ctx, ">=")) goto l94;  yyDo(ctx, yy_18_Punctuation, ctx->begin, ctx->end);  goto l72;
  l94:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '>')) goto l95;  yyDo(ctx, yy_19_Punctuation, ctx->begin, ctx->end);  goto l72;
  l95:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '=')) goto l96;
  {  int yypos97= ctx->pos, yythunkpos97= ctx->thunkpos;  if (!yymatchChar(ctx, '>')) goto l97;  goto l96;
  l97:;	  ctx->pos= yypos97; ctx->thunkpos= yythunkpos97;
  }  yyDo(ctx, yy_20_Punctuation, ctx->begin, ctx->end);  goto l72;
  l96:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchString(ctx, "=>")) goto l98;  yyDo(ctx, yy_21_Punctuation, ctx->begin, ctx->end);  goto l72;
  l98:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, ':')) goto l99;
  {  int yypos100= ctx->pos, yythunkpos100= ctx->thunkpos;  if (!yy_IDENT_START(ctx)) goto l100;  goto l99;
  l100:;	  ctx->pos= yypos100; ctx->thunkpos= yythunkpos100;
  }  yyDo(ctx, yy_22_Punctuation, ctx->begin, ctx->end);  goto l72;
  l99:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, ',')) goto l101;  yyDo(ctx, yy_23_Punctuation, ctx->begin, ctx->end);  goto l72;
  l101:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '.')) goto l102;  yyDo(ctx, yy_24_Punctuation, ctx->begin, ctx->end);  goto l72;
  l102:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '(')) goto l103;  yyDo(ctx, yy_25_Punctuation, ctx->begin, ctx->end);  goto l72;
  l103:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, ')')) goto l104;  yyDo(ctx, yy_26_Punctuation, ctx->begin, ctx->end);  goto l72;
  l104:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '{')) goto l105;  yyDo(ctx, yy_27_Punctuation, ctx->begin, ctx->end);  goto l72;
  l105:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '}')) goto l106;  yyDo(ctx, yy_28_Punctuation, ctx->begin, ctx->end);  goto l72;
  l106:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, '[')) goto l107;  yyDo(ctx, yy_29_Punctuation, ctx->begin, ctx->end);  goto l72;
  l107:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;  if (!yymatchChar(ctx, ']')) goto l71;  yyDo(ctx, yy_30_Punctuation, ctx->begin, ctx->end);
  }
  l72:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Punctuation", ctx->buf+ctx->pos));
  return 1;
  l71:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Punctuation", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_STRING(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "STRING"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l108;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l108;
  l109:;	
  {  int yypos110= ctx->pos, yythunkpos110= ctx->thunkpos;  if (!yy_STRING_CHAR(ctx)) goto l110;  goto l109;
  l110:;	  ctx->pos= yypos110; ctx->thunkpos= yythunkpos110;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l108;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l108;
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING", ctx->buf+ctx->pos));
  return 1;
  l108:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_INTEGER(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "INTEGER"));
  {  int yypos112= ctx->pos, yythunkpos112= ctx->thunkpos;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l113;  if (!yymatchChar(ctx, '0')) goto l113;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l113;
  {  int yypos114= ctx->pos, yythunkpos114= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\004\200\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l114;  goto l113;
  l114:;	  ctx->pos= yypos114; ctx->thunkpos= yythunkpos114;
  }  goto l112;
  l113:;	  ctx->pos= yypos112; ctx->thunkpos= yythunkpos112;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l115;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\376\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l115;
  l116:;	
  {  int yypos117= ctx->pos, yythunkpos117= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l117;  goto l116;
  l117:;	  ctx->pos= yypos117; ctx->thunkpos= yythunkpos117;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l115;  goto l112;
  l115:;	  ctx->pos= yypos112; ctx->thunkpos= yythunkpos112;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l118;  if (!yymatchString(ctx, "0x")) goto l118;  if (!yy_HEX_DIGIT(ctx)) goto l118;
  l119:;	
  {  int yypos120= ctx->pos, yythunkpos120= ctx->thunkpos;  if (!yy_HEX_DIGIT(ctx)) goto l120;  goto l119;
  l120:;	  ctx->pos= yypos120; ctx->thunkpos= yythunkpos120;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l118;  goto l112;
  l118:;	  ctx->pos= yypos112; ctx->thunkpos= yythunkpos112;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l121;  if (!yymatchString(ctx, "0o")) goto l121;  if (!yy_OCT_DIGIT(ctx)) goto l121;
  l122:;	
  {  int yypos123= ctx->pos, yythunkpos123= ctx->thunkpos;  if (!yy_OCT_DIGIT(ctx)) goto l123;  goto l122;
  l123:;	  ctx->pos= yypos123; ctx->thunkpos= yythunkpos123;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l121;  goto l112;
  l121:;	  ctx->pos= yypos112; ctx->thunkpos= yythunkpos112;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l111;  if (!yymatchString(ctx, "0b")) goto l111;  if (!yy_BIN_DIGIT(ctx)) goto l111;
  l124:;	
  {  int yypos125= ctx->pos, yythunkpos125= ctx->thunkpos;  if (!yy_BIN_DIGIT(ctx)) goto l125;  goto l124;
  l125:;	  ctx->pos= yypos125; ctx->thunkpos= yythunkpos125;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l111;
  }
  l112:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "INTEGER", ctx->buf+ctx->pos));
  return 1;
  l111:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "INTEGER", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Token(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Token"));
  {  int yypos127= ctx->pos, yythunkpos127= ctx->thunkpos;  if (!yy_INTEGER(ctx)) goto l128;  yyDo(ctx, yy_1_Token, ctx->begin, ctx->end);  goto l127;
  l128:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;  if (!yy_STRING(ctx)) goto l129;  yyDo(ctx, yy_2_Token, ctx->begin, ctx->end);  goto l127;
  l129:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;  if (!yy_Punctuation(ctx)) goto l130;  goto l127;
  l130:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;  if (!yy_Keyword(ctx)) goto l131;  goto l127;
  l131:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;  if (!yy_SYMBOL(ctx)) goto l132;  yyDo(ctx, yy_3_Token, ctx->begin, ctx->end);  goto l127;
  l132:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;  if (!yy_IDENT(ctx)) goto l133;  yyDo(ctx, yy_4_Token, ctx->begin, ctx->end);  goto l127;
  l133:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;  if (!yy_WHITESPACE(ctx)) goto l134;  yyDo(ctx, yy_5_Token, ctx->begin, ctx->end);  goto l127;
  l134:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;  if (!yy_EOL(ctx)) goto l135;  yyDo(ctx, yy_6_Token, ctx->begin, ctx->end);  goto l127;
  l135:;	  ctx->pos= yypos127; ctx->thunkpos= yythunkpos127;  if (!yy_EOF(ctx)) goto l126;  yyDo(ctx, yy_7_Token, ctx->begin, ctx->end);
  }
  l127:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Token", ctx->buf+ctx->pos));
  return 1;
  l126:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Token", ctx->buf+ctx->pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *ctx);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->buflen)
    {
      yyctx->buflen= 1024;
      yyctx->buf= (char *)malloc(yyctx->buflen);
      yyctx->textlen= 1024;
      yyctx->text= (char *)malloc(yyctx->textlen);
      yyctx->thunkslen= 32;
      yyctx->thunks= (yythunk *)malloc(sizeof(yythunk) * yyctx->thunkslen);
      yyctx->valslen= 32;
      yyctx->vals= (YYSTYPE *)malloc(sizeof(YYSTYPE) * yyctx->valslen);
      yyctx->begin= yyctx->end= yyctx->pos= yyctx->limit= yyctx->thunkpos= 0;
    }
  yyctx->begin= yyctx->end= yyctx->pos;
  yyctx->thunkpos= 0;
  yyctx->val= yyctx->vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_Token);
}

#endif


static token_t dequeue_pending_dent(yycontext *ctx) {
    ctx->pending_dents--;
    return ctx->pending_is_indent ? T_INDENT : T_OUTDENT;
}

static int handle_leading_whitespace(yycontext *ctx, int len) {
    int indent = 0;
    for (int i = 0; i < len; i++) {
        indent++;
        // if (ctx->text[i] == '\t') {
        //     indent = (indent + 1) & 0x03; // check
        // }
    }
    
    if (indent == CURRENT_INDENT) {
        return 1;
    } else if (indent > CURRENT_INDENT) { // indent
        ctx->indent_depth++;
        if (ctx->indent_depth == MAX_INDENT) {
            ctx->error = "maximum indent depth exceeded";
            return 0;
        } else {
            ctx->indents[ctx->indent_depth] = indent;
            ctx->pending_dents = 1;
            ctx->pending_is_indent = 1;
            return 1;
        }
    } else { // outdent
        ctx->pending_dents = 0;
        ctx->pending_is_indent = 0;
        while (1) {
            ctx->pending_dents++;
            ctx->indent_depth--;
            if (indent == CURRENT_INDENT) {
                return 1;
            } else if (indent > CURRENT_INDENT) {
                ctx->error = "indentation error";
                return 0;
            }
        }
    }
}

scanner_t* scanner_create_for_file(FILE *file) {
    yycontext *ctx = malloc(sizeof(yycontext));
    if (ctx) {
        ctx->text               = malloc(16);
        ctx->text[0]            = '\0';
        ctx->textlen            = 16;
        ctx->file               = file;
        ctx->indent_depth       = 1;
        ctx->indents[0]         = 0;
        ctx->pending_dents      = 1;
        ctx->pending_is_indent  = 1;
        ctx->pushback_token     = 0;
        ctx->is_eof             = 0;
        ctx->was_newline        = 0;
        ctx->error              = NULL;
    }
    return (scanner_t*)ctx;
}

void scanner_destroy(scanner_t *s) {
    yycontext *ctx = (yycontext*)s;
    if (ctx->buf)       free(ctx->buf);
    if (ctx->text)      free(ctx->text);
    if (ctx->thunks)    free(ctx->thunks);
    if (ctx->vals)      free(ctx->vals);
    free(ctx);
}

token_t scanner_get_next_token(scanner_t *s, char **text, int *len) {

    yycontext *ctx = (yycontext*)s;
    
    token_t out_token;
    
    if (ctx->error) {
        out_token = T_ERROR;
        
    } else if (ctx->pending_dents > 0) {
        out_token = dequeue_pending_dent(ctx);
        
    } else if (ctx->pushback_token) {
        out_token = ctx->pushback_token;
        ctx->pushback_token = 0;
        
    } else if (ctx->is_eof) {
        out_token = T_EOF;
        
    } else {
        while (1) {
            if (!yyparse(ctx)) {
                ctx->error = "parse error";
                out_token = T_ERROR;
                break;
            }
            
            if (ctx->yy == T_EOF) {
                ctx->is_eof = 1;
                
                // TODO: sanity check; technically there should be pending outdents
                ctx->pending_dents = ctx->indent_depth - 1;
                ctx->pending_is_indent = 0;
                out_token = T_OUTDENT;
                
                /* ensure every input line has an EOL so that statements are terminated */
                if (!ctx->was_newline) {
                    ctx->pending_dents++;
                    out_token = T_EOL;
                }
                
                break;
            
            } else if (ctx->yy == T_EOL) {
                out_token = T_EOL;
                break;
            
            } else if (ctx->was_newline) {
                if (ctx->yy == T_WHITESPACE) {
                    int res = handle_leading_whitespace(ctx, strlen(ctx->text));
                    if (!res) {
                        out_token = T_ERROR;
                        break;
                    } else if (ctx->pending_dents > 0) {
                        out_token = dequeue_pending_dent(ctx);
                        break;
                    } else {
                        ctx->was_newline = 0;
                        continue;
                    }
                } else {
                    int res = handle_leading_whitespace(ctx, 0);
                    if (!res) {
                        out_token = T_ERROR;
                        break;
                    } else if (ctx->pending_dents > 0) {
                        ctx->pushback_token = ctx->yy;
                        out_token = dequeue_pending_dent(ctx);
                        break;
                    } else {
                        out_token = ctx->yy;
                        break;
                    }
                }
            
            } else {
                out_token = ctx->yy;
                break;
            
            }
        }
    }
    
    ctx->was_newline = (out_token == T_EOL);
    
    if (text)   *text   = ctx->text;
    if (len)    *len    = strlen(ctx->text);
    
    return out_token;
    
}

