/* A recursive-descent parser generated by peg 0.1.9 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 18

#include "menace/scanner.h"
#include <stdio.h>

#define YY_INPUT(buf, result, max_size)             \
{                                                   \
    int yyc = getc(ctx->file);                      \
    result = (EOF == yyc) ? 0 : (*(buf)=yyc, 1);    \
}

#define YY_CTX_LOCAL
#define YYSTYPE             token_t
#define YY_PARSE(T)         static T
#define MAX_INDENT          32
#define CURRENT_INDENT      (ctx->indents[ctx->indent_depth])

#define YY_CTX_MEMBERS                                  \
    FILE                *file;                          \
    int                 indent_depth;                   \
    int                 indents[MAX_INDENT];            \
    int                 pending_dents;                  \
    int                 pending_is_indent;              \
    token_t             pushback_token;                 \
    char                is_eof;                         \
    char                was_newline;                    \
    char                *error;

#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( ctx->begin= ctx->pos, 1)
#endif
#ifndef YY_END
#define YY_END		( ctx->end= ctx->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *ctx, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *buf;
  int       buflen;
  int       pos;
  int       limit;
  char     *text;
  int       textlen;
  int       begin;
  int       end;
  int       textmax;
  yythunk  *thunks;
  int       thunkslen;
  int       thunkpos;
  YYSTYPE   yy;
  YYSTYPE  *val;
  YYSTYPE  *vals;
  int       valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext yyctx0;
yycontext *yyctx= &yyctx0;
#endif

YY_LOCAL(int) yyrefill(yycontext *ctx)
{
  int yyn;
  while (ctx->buflen - ctx->pos < 512)
    {
      ctx->buflen *= 2;
      ctx->buf= (char *)realloc(ctx->buf, ctx->buflen);
    }
  YY_INPUT((ctx->buf + ctx->pos), yyn, (ctx->buflen - ctx->pos));
  if (!yyn) return 0;
  ctx->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *ctx)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  ++ctx->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *ctx, int c)
{
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  if ((unsigned char)ctx->buf[ctx->pos] == c)
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchChar(ctx, %c) @ %s\n", c, ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(ctx, %c) @ %s\n", c, ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *ctx, char *s)
{
  int yysav= ctx->pos;
  while (*s)
    {
      if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
      if (ctx->buf[ctx->pos] != *s)
        {
          ctx->pos= yysav;
          return 0;
        }
      ++s;
      ++ctx->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *ctx, unsigned char *bits)
{
  int c;
  if (ctx->pos >= ctx->limit && !yyrefill(ctx)) return 0;
  c= (unsigned char)ctx->buf[ctx->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++ctx->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", ctx->buf+ctx->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", ctx->buf+ctx->pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *ctx, yyaction action, int begin, int end)
{
  while (ctx->thunkpos >= ctx->thunkslen)
    {
      ctx->thunkslen *= 2;
      ctx->thunks= (yythunk *)realloc(ctx->thunks, sizeof(yythunk) * ctx->thunkslen);
    }
  ctx->thunks[ctx->thunkpos].begin=  begin;
  ctx->thunks[ctx->thunkpos].end=    end;
  ctx->thunks[ctx->thunkpos].action= action;
  ++ctx->thunkpos;
}

YY_LOCAL(int) yyText(yycontext *ctx, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (ctx->textlen < (yyleng + 1))
	{
	  ctx->textlen *= 2;
	  ctx->text= (char *)realloc(ctx->text, ctx->textlen);
	}
      memcpy(ctx->text, ctx->buf + begin, yyleng);
    }
  ctx->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *ctx)
{
  int pos;
  for (pos= 0;  pos < ctx->thunkpos;  ++pos)
    {
      yythunk *thunk= &ctx->thunks[pos];
      int yyleng= thunk->end ? yyText(ctx, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, ctx->text));
      thunk->action(ctx, ctx->text, yyleng);
    }
  ctx->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *ctx)
{
  if ((ctx->limit -= ctx->pos))
    {
      memmove(ctx->buf, ctx->buf + ctx->pos, ctx->limit);
    }
  ctx->begin -= ctx->pos;
  ctx->end -= ctx->pos;
  ctx->pos= ctx->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *ctx, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(ctx);
      yyCommit(ctx);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *ctx, char *text, int count)  { ctx->val += count; }
YY_LOCAL(void) yyPop(yycontext *ctx, char *text, int count)   { ctx->val -= count; }
YY_LOCAL(void) yySet(yycontext *ctx, char *text, int count)   { ctx->val[count]= ctx->yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(ctx, yythunkpos0)

YY_RULE(int) yy_ESCAPE(yycontext *ctx); /* 18 */
YY_RULE(int) yy_NON_PRINTABLE(yycontext *ctx); /* 17 */
YY_RULE(int) yy_IDENT_REST(yycontext *ctx); /* 16 */
YY_RULE(int) yy_IDENT_START(yycontext *ctx); /* 15 */
YY_RULE(int) yy_STRING_CHAR(yycontext *ctx); /* 14 */
YY_RULE(int) yy_BIN_DIGIT(yycontext *ctx); /* 13 */
YY_RULE(int) yy_OCT_DIGIT(yycontext *ctx); /* 12 */
YY_RULE(int) yy_HEX_DIGIT(yycontext *ctx); /* 11 */
YY_RULE(int) yy_EOF(yycontext *ctx); /* 10 */
YY_RULE(int) yy_EOL(yycontext *ctx); /* 9 */
YY_RULE(int) yy_WHITESPACE(yycontext *ctx); /* 8 */
YY_RULE(int) yy_IDENT(yycontext *ctx); /* 7 */
YY_RULE(int) yy_SYMBOL(yycontext *ctx); /* 6 */
YY_RULE(int) yy_Keyword(yycontext *ctx); /* 5 */
YY_RULE(int) yy_Punctuation(yycontext *ctx); /* 4 */
YY_RULE(int) yy_STRING(yycontext *ctx); /* 3 */
YY_RULE(int) yy_INTEGER(yycontext *ctx); /* 2 */
YY_RULE(int) yy_Token(yycontext *ctx); /* 1 */

YY_ACTION(void) yy_12_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_12_Keyword\n"));
   yy = T_NOT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_11_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_11_Keyword\n"));
   yy = T_OR ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_10_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_10_Keyword\n"));
   yy = T_AND ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_9_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_9_Keyword\n"));
   yy = T_RETURN ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_8_Keyword\n"));
   yy = T_PASS ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_7_Keyword\n"));
   yy = T_FALSE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_6_Keyword\n"));
   yy = T_TRUE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_5_Keyword\n"));
   yy = T_ELSE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_4_Keyword\n"));
   yy = T_ELSEIF ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_3_Keyword\n"));
   yy = T_IF ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_2_Keyword\n"));
   yy = T_WHILE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Keyword(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_Keyword\n"));
   yy = T_DEF ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_30_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_30_Punctuation\n"));
   yy = T_R_BRACKET ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_29_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_29_Punctuation\n"));
   yy = T_L_BRACKET ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_28_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_28_Punctuation\n"));
   yy = T_R_BRACE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_27_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_27_Punctuation\n"));
   yy = T_L_BRACE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_26_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_26_Punctuation\n"));
   yy = T_R_PAREN ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_25_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_25_Punctuation\n"));
   yy = T_L_PAREN ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_24_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_24_Punctuation\n"));
   yy = T_DOT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_23_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_23_Punctuation\n"));
   yy = T_COMMA ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_22_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_22_Punctuation\n"));
   yy = T_COLON ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_21_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_21_Punctuation\n"));
   yy = T_HASHROCKET ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_20_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_20_Punctuation\n"));
   yy = T_EQUALS ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_19_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_19_Punctuation\n"));
   yy = T_GT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_18_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_18_Punctuation\n"));
   yy = T_GTE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_17_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_17_Punctuation\n"));
   yy = T_LTE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_16_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_16_Punctuation\n"));
   yy = T_LT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_15_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_15_Punctuation\n"));
   yy = T_NEQ ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_14_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_14_Punctuation\n"));
   yy = T_EQ ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_13_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_13_Punctuation\n"));
   yy = T_DBL_PIPE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_12_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_12_Punctuation\n"));
   yy = T_DBL_AMPERSAND ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_11_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_11_Punctuation\n"));
   yy = T_PIPE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_10_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_10_Punctuation\n"));
   yy = T_AMPERSAND ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_9_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_9_Punctuation\n"));
   yy = T_BANG ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_8_Punctuation\n"));
   yy = T_HAT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_7_Punctuation\n"));
   yy = T_TILDE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_6_Punctuation\n"));
   yy = T_POW ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_5_Punctuation\n"));
   yy = T_MOD ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_4_Punctuation\n"));
   yy = T_DIV ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_3_Punctuation\n"));
   yy = T_TIMES ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_2_Punctuation\n"));
   yy = T_MINUS ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Punctuation(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_Punctuation\n"));
   yy = T_PLUS ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_7_Token\n"));
   yy = T_EOF ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_6_Token\n"));
   yy = T_EOL ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_5_Token\n"));
   yy = T_WHITESPACE ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_4_Token\n"));
   yy = T_IDENT ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_3_Token\n"));
   yy = T_SYMBOL ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_2_Token\n"));
   yy = T_STRING ;
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Token(yycontext *ctx, char *yytext, int yyleng)
{
#define yy ctx->yy
#define yypos ctx->pos
#define yythunkpos ctx->thunkpos
  yyprintf((stderr, "do yy_1_Token\n"));
   yy = T_INTEGER ;
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_ESCAPE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "ESCAPE"));  if (!yymatchChar(ctx, '\\')) goto l1;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\204\000\000\000\000\000\000\020\104\100\024\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "ESCAPE", ctx->buf+ctx->pos));
  return 1;
  l1:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ESCAPE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_NON_PRINTABLE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "NON_PRINTABLE"));
  {  int yypos3= ctx->pos, yythunkpos3= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\377\377\377\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;  goto l3;
  l4:;	  ctx->pos= yypos3; ctx->thunkpos= yythunkpos3;  if (!yymatchString(ctx, "\177")) goto l2;
  }
  l3:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NON_PRINTABLE", ctx->buf+ctx->pos));
  return 1;
  l2:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NON_PRINTABLE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_IDENT_REST(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IDENT_REST"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT_REST", ctx->buf+ctx->pos));
  return 1;
  l5:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT_REST", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_IDENT_START(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IDENT_START"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT_START", ctx->buf+ctx->pos));
  return 1;
  l6:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT_START", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_STRING_CHAR(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "STRING_CHAR"));
  {  int yypos8= ctx->pos, yythunkpos8= ctx->thunkpos;  if (!yy_ESCAPE(ctx)) goto l9;  goto l8;
  l9:;	  ctx->pos= yypos8; ctx->thunkpos= yythunkpos8;
  {  int yypos10= ctx->pos, yythunkpos10= ctx->thunkpos;  if (!yymatchChar(ctx, '\\')) goto l10;  goto l7;
  l10:;	  ctx->pos= yypos10; ctx->thunkpos= yythunkpos10;
  }
  {  int yypos11= ctx->pos, yythunkpos11= ctx->thunkpos;  if (!yymatchChar(ctx, '"')) goto l11;  goto l7;
  l11:;	  ctx->pos= yypos11; ctx->thunkpos= yythunkpos11;
  }
  {  int yypos12= ctx->pos, yythunkpos12= ctx->thunkpos;  if (!yy_NON_PRINTABLE(ctx)) goto l12;  goto l7;
  l12:;	  ctx->pos= yypos12; ctx->thunkpos= yythunkpos12;
  }  if (!yymatchDot(ctx)) goto l7;
  }
  l8:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING_CHAR", ctx->buf+ctx->pos));
  return 1;
  l7:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING_CHAR", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_BIN_DIGIT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "BIN_DIGIT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l13;
  yyprintf((stderr, "  ok   %s @ %s\n", "BIN_DIGIT", ctx->buf+ctx->pos));
  return 1;
  l13:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BIN_DIGIT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_OCT_DIGIT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "OCT_DIGIT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;
  yyprintf((stderr, "  ok   %s @ %s\n", "OCT_DIGIT", ctx->buf+ctx->pos));
  return 1;
  l14:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OCT_DIGIT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_HEX_DIGIT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "HEX_DIGIT"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l15;
  yyprintf((stderr, "  ok   %s @ %s\n", "HEX_DIGIT", ctx->buf+ctx->pos));
  return 1;
  l15:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "HEX_DIGIT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos17= ctx->pos, yythunkpos17= ctx->thunkpos;  if (!yymatchDot(ctx)) goto l17;  goto l16;
  l17:;	  ctx->pos= yypos17; ctx->thunkpos= yythunkpos17;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", ctx->buf+ctx->pos));
  return 1;
  l16:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_EOL(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos19= ctx->pos, yythunkpos19= ctx->thunkpos;  if (!yymatchString(ctx, "\r\n")) goto l20;  goto l19;
  l20:;	  ctx->pos= yypos19; ctx->thunkpos= yythunkpos19;  if (!yymatchChar(ctx, '\n')) goto l21;  goto l19;
  l21:;	  ctx->pos= yypos19; ctx->thunkpos= yythunkpos19;  if (!yymatchChar(ctx, '\r')) goto l18;
  }
  l19:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", ctx->buf+ctx->pos));
  return 1;
  l18:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_WHITESPACE(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "WHITESPACE"));  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l22;
  {  int yypos25= ctx->pos, yythunkpos25= ctx->thunkpos;  if (!yymatchChar(ctx, ' ')) goto l26;  goto l25;
  l26:;	  ctx->pos= yypos25; ctx->thunkpos= yythunkpos25;  if (!yymatchChar(ctx, '\t')) goto l22;
  }
  l25:;	
  l23:;	
  {  int yypos24= ctx->pos, yythunkpos24= ctx->thunkpos;
  {  int yypos27= ctx->pos, yythunkpos27= ctx->thunkpos;  if (!yymatchChar(ctx, ' ')) goto l28;  goto l27;
  l28:;	  ctx->pos= yypos27; ctx->thunkpos= yythunkpos27;  if (!yymatchChar(ctx, '\t')) goto l24;
  }
  l27:;	  goto l23;
  l24:;	  ctx->pos= yypos24; ctx->thunkpos= yythunkpos24;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l22;
  yyprintf((stderr, "  ok   %s @ %s\n", "WHITESPACE", ctx->buf+ctx->pos));
  return 1;
  l22:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WHITESPACE", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_IDENT(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "IDENT"));  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l29;  if (!yy_IDENT_START(ctx)) goto l29;
  l30:;	
  {  int yypos31= ctx->pos, yythunkpos31= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l31;  goto l30;
  l31:;	  ctx->pos= yypos31; ctx->thunkpos= yythunkpos31;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l29;
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT", ctx->buf+ctx->pos));
  return 1;
  l29:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_SYMBOL(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "SYMBOL"));  if (!yymatchChar(ctx, ':')) goto l32;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l32;  if (!yy_IDENT_START(ctx)) goto l32;
  l33:;	
  {  int yypos34= ctx->pos, yythunkpos34= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l34;  goto l33;
  l34:;	  ctx->pos= yypos34; ctx->thunkpos= yythunkpos34;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l32;
  yyprintf((stderr, "  ok   %s @ %s\n", "SYMBOL", ctx->buf+ctx->pos));
  return 1;
  l32:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SYMBOL", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Keyword(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Keyword"));
  {  int yypos36= ctx->pos, yythunkpos36= ctx->thunkpos;  if (!yymatchString(ctx, "def")) goto l37;
  {  int yypos38= ctx->pos, yythunkpos38= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l38;  goto l37;
  l38:;	  ctx->pos= yypos38; ctx->thunkpos= yythunkpos38;
  }  yyDo(ctx, yy_1_Keyword, ctx->begin, ctx->end);  goto l36;
  l37:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "while")) goto l39;
  {  int yypos40= ctx->pos, yythunkpos40= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l40;  goto l39;
  l40:;	  ctx->pos= yypos40; ctx->thunkpos= yythunkpos40;
  }  yyDo(ctx, yy_2_Keyword, ctx->begin, ctx->end);  goto l36;
  l39:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "if")) goto l41;
  {  int yypos42= ctx->pos, yythunkpos42= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l42;  goto l41;
  l42:;	  ctx->pos= yypos42; ctx->thunkpos= yythunkpos42;
  }  yyDo(ctx, yy_3_Keyword, ctx->begin, ctx->end);  goto l36;
  l41:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "elseif")) goto l43;
  {  int yypos44= ctx->pos, yythunkpos44= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l44;  goto l43;
  l44:;	  ctx->pos= yypos44; ctx->thunkpos= yythunkpos44;
  }  yyDo(ctx, yy_4_Keyword, ctx->begin, ctx->end);  goto l36;
  l43:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "else")) goto l45;
  {  int yypos46= ctx->pos, yythunkpos46= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l46;  goto l45;
  l46:;	  ctx->pos= yypos46; ctx->thunkpos= yythunkpos46;
  }  yyDo(ctx, yy_5_Keyword, ctx->begin, ctx->end);  goto l36;
  l45:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "true")) goto l47;
  {  int yypos48= ctx->pos, yythunkpos48= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l48;  goto l47;
  l48:;	  ctx->pos= yypos48; ctx->thunkpos= yythunkpos48;
  }  yyDo(ctx, yy_6_Keyword, ctx->begin, ctx->end);  goto l36;
  l47:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "false")) goto l49;
  {  int yypos50= ctx->pos, yythunkpos50= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l50;  goto l49;
  l50:;	  ctx->pos= yypos50; ctx->thunkpos= yythunkpos50;
  }  yyDo(ctx, yy_7_Keyword, ctx->begin, ctx->end);  goto l36;
  l49:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "pass")) goto l51;
  {  int yypos52= ctx->pos, yythunkpos52= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l52;  goto l51;
  l52:;	  ctx->pos= yypos52; ctx->thunkpos= yythunkpos52;
  }  yyDo(ctx, yy_8_Keyword, ctx->begin, ctx->end);  goto l36;
  l51:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "return")) goto l53;
  {  int yypos54= ctx->pos, yythunkpos54= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l54;  goto l53;
  l54:;	  ctx->pos= yypos54; ctx->thunkpos= yythunkpos54;
  }  yyDo(ctx, yy_9_Keyword, ctx->begin, ctx->end);  goto l36;
  l53:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "and")) goto l55;
  {  int yypos56= ctx->pos, yythunkpos56= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l56;  goto l55;
  l56:;	  ctx->pos= yypos56; ctx->thunkpos= yythunkpos56;
  }  yyDo(ctx, yy_10_Keyword, ctx->begin, ctx->end);  goto l36;
  l55:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "or")) goto l57;
  {  int yypos58= ctx->pos, yythunkpos58= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l58;  goto l57;
  l58:;	  ctx->pos= yypos58; ctx->thunkpos= yythunkpos58;
  }  yyDo(ctx, yy_11_Keyword, ctx->begin, ctx->end);  goto l36;
  l57:;	  ctx->pos= yypos36; ctx->thunkpos= yythunkpos36;  if (!yymatchString(ctx, "not")) goto l35;
  {  int yypos59= ctx->pos, yythunkpos59= ctx->thunkpos;  if (!yy_IDENT_REST(ctx)) goto l59;  goto l35;
  l59:;	  ctx->pos= yypos59; ctx->thunkpos= yythunkpos59;
  }  yyDo(ctx, yy_12_Keyword, ctx->begin, ctx->end);
  }
  l36:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Keyword", ctx->buf+ctx->pos));
  return 1;
  l35:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Keyword", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Punctuation(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Punctuation"));
  {  int yypos61= ctx->pos, yythunkpos61= ctx->thunkpos;  if (!yymatchChar(ctx, '+')) goto l62;  yyDo(ctx, yy_1_Punctuation, ctx->begin, ctx->end);  goto l61;
  l62:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '-')) goto l63;  yyDo(ctx, yy_2_Punctuation, ctx->begin, ctx->end);  goto l61;
  l63:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '*')) goto l64;
  {  int yypos65= ctx->pos, yythunkpos65= ctx->thunkpos;  if (!yymatchChar(ctx, '*')) goto l65;  goto l64;
  l65:;	  ctx->pos= yypos65; ctx->thunkpos= yythunkpos65;
  }  yyDo(ctx, yy_3_Punctuation, ctx->begin, ctx->end);  goto l61;
  l64:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '/')) goto l66;  yyDo(ctx, yy_4_Punctuation, ctx->begin, ctx->end);  goto l61;
  l66:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '%')) goto l67;  yyDo(ctx, yy_5_Punctuation, ctx->begin, ctx->end);  goto l61;
  l67:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchString(ctx, "**")) goto l68;  yyDo(ctx, yy_6_Punctuation, ctx->begin, ctx->end);  goto l61;
  l68:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '~')) goto l69;  yyDo(ctx, yy_7_Punctuation, ctx->begin, ctx->end);  goto l61;
  l69:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '^')) goto l70;  yyDo(ctx, yy_8_Punctuation, ctx->begin, ctx->end);  goto l61;
  l70:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '!')) goto l71;
  {  int yypos72= ctx->pos, yythunkpos72= ctx->thunkpos;  if (!yymatchChar(ctx, '=')) goto l72;  goto l71;
  l72:;	  ctx->pos= yypos72; ctx->thunkpos= yythunkpos72;
  }  yyDo(ctx, yy_9_Punctuation, ctx->begin, ctx->end);  goto l61;
  l71:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '&')) goto l73;
  {  int yypos74= ctx->pos, yythunkpos74= ctx->thunkpos;  if (!yymatchChar(ctx, '&')) goto l74;  goto l73;
  l74:;	  ctx->pos= yypos74; ctx->thunkpos= yythunkpos74;
  }  yyDo(ctx, yy_10_Punctuation, ctx->begin, ctx->end);  goto l61;
  l73:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '|')) goto l75;
  {  int yypos76= ctx->pos, yythunkpos76= ctx->thunkpos;  if (!yymatchChar(ctx, '|')) goto l76;  goto l75;
  l76:;	  ctx->pos= yypos76; ctx->thunkpos= yythunkpos76;
  }  yyDo(ctx, yy_11_Punctuation, ctx->begin, ctx->end);  goto l61;
  l75:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchString(ctx, "&&")) goto l77;  yyDo(ctx, yy_12_Punctuation, ctx->begin, ctx->end);  goto l61;
  l77:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchString(ctx, "||")) goto l78;  yyDo(ctx, yy_13_Punctuation, ctx->begin, ctx->end);  goto l61;
  l78:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchString(ctx, "==")) goto l79;  yyDo(ctx, yy_14_Punctuation, ctx->begin, ctx->end);  goto l61;
  l79:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchString(ctx, "!=")) goto l80;  yyDo(ctx, yy_15_Punctuation, ctx->begin, ctx->end);  goto l61;
  l80:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '<')) goto l81;  yyDo(ctx, yy_16_Punctuation, ctx->begin, ctx->end);  goto l61;
  l81:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchString(ctx, "<=")) goto l82;  yyDo(ctx, yy_17_Punctuation, ctx->begin, ctx->end);  goto l61;
  l82:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchString(ctx, ">=")) goto l83;  yyDo(ctx, yy_18_Punctuation, ctx->begin, ctx->end);  goto l61;
  l83:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '>')) goto l84;  yyDo(ctx, yy_19_Punctuation, ctx->begin, ctx->end);  goto l61;
  l84:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '=')) goto l85;
  {  int yypos86= ctx->pos, yythunkpos86= ctx->thunkpos;  if (!yymatchChar(ctx, '>')) goto l86;  goto l85;
  l86:;	  ctx->pos= yypos86; ctx->thunkpos= yythunkpos86;
  }  yyDo(ctx, yy_20_Punctuation, ctx->begin, ctx->end);  goto l61;
  l85:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchString(ctx, "=>")) goto l87;  yyDo(ctx, yy_21_Punctuation, ctx->begin, ctx->end);  goto l61;
  l87:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, ':')) goto l88;
  {  int yypos89= ctx->pos, yythunkpos89= ctx->thunkpos;  if (!yy_IDENT_START(ctx)) goto l89;  goto l88;
  l89:;	  ctx->pos= yypos89; ctx->thunkpos= yythunkpos89;
  }  yyDo(ctx, yy_22_Punctuation, ctx->begin, ctx->end);  goto l61;
  l88:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, ',')) goto l90;  yyDo(ctx, yy_23_Punctuation, ctx->begin, ctx->end);  goto l61;
  l90:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '.')) goto l91;  yyDo(ctx, yy_24_Punctuation, ctx->begin, ctx->end);  goto l61;
  l91:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '(')) goto l92;  yyDo(ctx, yy_25_Punctuation, ctx->begin, ctx->end);  goto l61;
  l92:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, ')')) goto l93;  yyDo(ctx, yy_26_Punctuation, ctx->begin, ctx->end);  goto l61;
  l93:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '{')) goto l94;  yyDo(ctx, yy_27_Punctuation, ctx->begin, ctx->end);  goto l61;
  l94:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '}')) goto l95;  yyDo(ctx, yy_28_Punctuation, ctx->begin, ctx->end);  goto l61;
  l95:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, '[')) goto l96;  yyDo(ctx, yy_29_Punctuation, ctx->begin, ctx->end);  goto l61;
  l96:;	  ctx->pos= yypos61; ctx->thunkpos= yythunkpos61;  if (!yymatchChar(ctx, ']')) goto l60;  yyDo(ctx, yy_30_Punctuation, ctx->begin, ctx->end);
  }
  l61:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Punctuation", ctx->buf+ctx->pos));
  return 1;
  l60:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Punctuation", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_STRING(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "STRING"));  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l97;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l97;
  l98:;	
  {  int yypos99= ctx->pos, yythunkpos99= ctx->thunkpos;  if (!yy_STRING_CHAR(ctx)) goto l99;  goto l98;
  l99:;	  ctx->pos= yypos99; ctx->thunkpos= yythunkpos99;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l97;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l97;
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING", ctx->buf+ctx->pos));
  return 1;
  l97:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_INTEGER(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "INTEGER"));
  {  int yypos101= ctx->pos, yythunkpos101= ctx->thunkpos;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l102;  if (!yymatchChar(ctx, '0')) goto l102;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l102;
  {  int yypos103= ctx->pos, yythunkpos103= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\004\200\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l103;  goto l102;
  l103:;	  ctx->pos= yypos103; ctx->thunkpos= yythunkpos103;
  }  goto l101;
  l102:;	  ctx->pos= yypos101; ctx->thunkpos= yythunkpos101;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l104;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\376\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l104;
  l105:;	
  {  int yypos106= ctx->pos, yythunkpos106= ctx->thunkpos;  if (!yymatchClass(ctx, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l106;  goto l105;
  l106:;	  ctx->pos= yypos106; ctx->thunkpos= yythunkpos106;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l104;  goto l101;
  l104:;	  ctx->pos= yypos101; ctx->thunkpos= yythunkpos101;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l107;  if (!yymatchString(ctx, "0x")) goto l107;  if (!yy_HEX_DIGIT(ctx)) goto l107;
  l108:;	
  {  int yypos109= ctx->pos, yythunkpos109= ctx->thunkpos;  if (!yy_HEX_DIGIT(ctx)) goto l109;  goto l108;
  l109:;	  ctx->pos= yypos109; ctx->thunkpos= yythunkpos109;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l107;  goto l101;
  l107:;	  ctx->pos= yypos101; ctx->thunkpos= yythunkpos101;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l110;  if (!yymatchString(ctx, "0o")) goto l110;  if (!yy_OCT_DIGIT(ctx)) goto l110;
  l111:;	
  {  int yypos112= ctx->pos, yythunkpos112= ctx->thunkpos;  if (!yy_OCT_DIGIT(ctx)) goto l112;  goto l111;
  l112:;	  ctx->pos= yypos112; ctx->thunkpos= yythunkpos112;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l110;  goto l101;
  l110:;	  ctx->pos= yypos101; ctx->thunkpos= yythunkpos101;  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_BEGIN)) goto l100;  if (!yymatchString(ctx, "0b")) goto l100;  if (!yy_BIN_DIGIT(ctx)) goto l100;
  l113:;	
  {  int yypos114= ctx->pos, yythunkpos114= ctx->thunkpos;  if (!yy_BIN_DIGIT(ctx)) goto l114;  goto l113;
  l114:;	  ctx->pos= yypos114; ctx->thunkpos= yythunkpos114;
  }  yyText(ctx, ctx->begin, ctx->end);  if (!(YY_END)) goto l100;
  }
  l101:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "INTEGER", ctx->buf+ctx->pos));
  return 1;
  l100:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "INTEGER", ctx->buf+ctx->pos));
  return 0;
}
YY_RULE(int) yy_Token(yycontext *ctx)
{  int yypos0= ctx->pos, yythunkpos0= ctx->thunkpos;
  yyprintf((stderr, "%s\n", "Token"));
  {  int yypos116= ctx->pos, yythunkpos116= ctx->thunkpos;  if (!yy_INTEGER(ctx)) goto l117;  yyDo(ctx, yy_1_Token, ctx->begin, ctx->end);  goto l116;
  l117:;	  ctx->pos= yypos116; ctx->thunkpos= yythunkpos116;  if (!yy_STRING(ctx)) goto l118;  yyDo(ctx, yy_2_Token, ctx->begin, ctx->end);  goto l116;
  l118:;	  ctx->pos= yypos116; ctx->thunkpos= yythunkpos116;  if (!yy_Punctuation(ctx)) goto l119;  goto l116;
  l119:;	  ctx->pos= yypos116; ctx->thunkpos= yythunkpos116;  if (!yy_Keyword(ctx)) goto l120;  goto l116;
  l120:;	  ctx->pos= yypos116; ctx->thunkpos= yythunkpos116;  if (!yy_SYMBOL(ctx)) goto l121;  yyDo(ctx, yy_3_Token, ctx->begin, ctx->end);  goto l116;
  l121:;	  ctx->pos= yypos116; ctx->thunkpos= yythunkpos116;  if (!yy_IDENT(ctx)) goto l122;  yyDo(ctx, yy_4_Token, ctx->begin, ctx->end);  goto l116;
  l122:;	  ctx->pos= yypos116; ctx->thunkpos= yythunkpos116;  if (!yy_WHITESPACE(ctx)) goto l123;  yyDo(ctx, yy_5_Token, ctx->begin, ctx->end);  goto l116;
  l123:;	  ctx->pos= yypos116; ctx->thunkpos= yythunkpos116;  if (!yy_EOL(ctx)) goto l124;  yyDo(ctx, yy_6_Token, ctx->begin, ctx->end);  goto l116;
  l124:;	  ctx->pos= yypos116; ctx->thunkpos= yythunkpos116;  if (!yy_EOF(ctx)) goto l115;  yyDo(ctx, yy_7_Token, ctx->begin, ctx->end);
  }
  l116:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Token", ctx->buf+ctx->pos));
  return 1;
  l115:;	  ctx->pos= yypos0; ctx->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Token", ctx->buf+ctx->pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *ctx);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->buflen)
    {
      yyctx->buflen= 1024;
      yyctx->buf= (char *)malloc(yyctx->buflen);
      yyctx->textlen= 1024;
      yyctx->text= (char *)malloc(yyctx->textlen);
      yyctx->thunkslen= 32;
      yyctx->thunks= (yythunk *)malloc(sizeof(yythunk) * yyctx->thunkslen);
      yyctx->valslen= 32;
      yyctx->vals= (YYSTYPE *)malloc(sizeof(YYSTYPE) * yyctx->valslen);
      yyctx->begin= yyctx->end= yyctx->pos= yyctx->limit= yyctx->thunkpos= 0;
    }
  yyctx->begin= yyctx->end= yyctx->pos;
  yyctx->thunkpos= 0;
  yyctx->val= yyctx->vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_Token);
}

#endif


static token_t dequeue_pending_dent(yycontext *ctx) {
    ctx->pending_dents--;
    return ctx->pending_is_indent ? T_INDENT : T_OUTDENT;
}

static int handle_leading_whitespace(yycontext *ctx, int len) {
    int indent = 0;
    for (int i = 0; i < len; i++) {
        indent++;
        // if (ctx->text[i] == '\t') {
        //     indent = (indent + 1) & 0x03; // check
        // }
    }
    
    if (indent == CURRENT_INDENT) {
        return 1;
    } else if (indent > CURRENT_INDENT) { // indent
        ctx->indent_depth++;
        if (ctx->indent_depth == MAX_INDENT) {
            ctx->error = "maximum indent depth exceeded";
            return 0;
        } else {
            ctx->indents[ctx->indent_depth] = indent;
            ctx->pending_dents = 1;
            ctx->pending_is_indent = 1;
            return 1;
        }
    } else { // outdent
        ctx->pending_dents = 0;
        ctx->pending_is_indent = 0;
        while (1) {
            ctx->pending_dents++;
            ctx->indent_depth--;
            if (indent == CURRENT_INDENT) {
                return 1;
            } else if (indent > CURRENT_INDENT) {
                ctx->error = "indentation error";
                return 0;
            }
        }
    }
}

scanner_t* scanner_create_for_file(FILE *file) {
    yycontext *ctx = malloc(sizeof(yycontext));
    if (ctx) {
        ctx->text               = malloc(16);
        ctx->text[0]            = '\0';
        ctx->textlen            = 16;
        ctx->file               = file;
        ctx->indent_depth       = 1;
        ctx->indents[0]         = 0;
        ctx->pending_dents      = 1;
        ctx->pending_is_indent  = 1;
        ctx->pushback_token     = 0;
        ctx->is_eof             = 0;
        ctx->was_newline        = 0;
        ctx->error              = NULL;
    }
    return (scanner_t*)ctx;
}

void scanner_destroy(scanner_t *s) {
    yycontext *ctx = (yycontext*)s;
    if (ctx->buf)       free(ctx->buf);
    if (ctx->text)      free(ctx->text);
    if (ctx->thunks)    free(ctx->thunks);
    if (ctx->vals)      free(ctx->vals);
    free(ctx);
}

token_t scanner_get_next_token(scanner_t *s, char **text, int *len) {

    yycontext *ctx = (yycontext*)s;
    
    token_t out_token;
    
    if (ctx->error) {
        out_token = T_ERROR;
        
    } else if (ctx->pending_dents > 0) {
        out_token = dequeue_pending_dent(ctx);
        
    } else if (ctx->pushback_token) {
        out_token = ctx->pushback_token;
        ctx->pushback_token = 0;
        
    } else if (ctx->is_eof) {
        out_token = T_EOF;
        
    } else {
        while (1) {
            if (!yyparse(ctx)) {
                ctx->error = "parse error";
                out_token = T_ERROR;
                break;
            }
            
            if (ctx->yy == T_EOF) {
                ctx->is_eof = 1;
                
                // TODO: sanity check; technically there should be pending outdents
                ctx->pending_dents = ctx->indent_depth - 1;
                ctx->pending_is_indent = 0;
                out_token = T_OUTDENT;
                
                /* ensure every input line has an EOL so that statements are terminated */
                if (!ctx->was_newline) {
                    ctx->pending_dents++;
                    out_token = T_EOL;
                }
                
                break;
            
            } else if (ctx->yy == T_EOL) {
                out_token = T_EOL;
                break;
            
            } else if (ctx->was_newline) {
                if (ctx->yy == T_WHITESPACE) {
                    int res = handle_leading_whitespace(ctx, strlen(ctx->text));
                    if (!res) {
                        out_token = T_ERROR;
                        break;
                    } else if (ctx->pending_dents > 0) {
                        out_token = dequeue_pending_dent(ctx);
                        break;
                    } else {
                        ctx->was_newline = 0;
                        continue;
                    }
                } else {
                    int res = handle_leading_whitespace(ctx, 0);
                    if (!res) {
                        out_token = T_ERROR;
                        break;
                    } else if (ctx->pending_dents > 0) {
                        ctx->pushback_token = ctx->yy;
                        out_token = dequeue_pending_dent(ctx);
                        break;
                    } else {
                        out_token = ctx->yy;
                        break;
                    }
                }
            
            } else {
                out_token = ctx->yy;
                break;
            
            }
        }
    }
    
    ctx->was_newline = (out_token == T_EOL);
    
    if (text)   *text   = ctx->text;
    if (len)    *len    = strlen(ctx->text);
    
    return out_token;
    
}

